package co.com.tactusoft.crm.model.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AstTrunkDialpatternsId generated by hbm2java
 */
@Entity
@Table(name = "ast_trunk_dialpatterns", catalog = "crm_db")
public class AstTrunkDialpatterns implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int trunkid;
	private String matchPatternPrefix;
	private String matchPatternPass;
	private String prependDigits;
	private int seq;

	public AstTrunkDialpatterns() {
	}

	public AstTrunkDialpatterns(int trunkid, String matchPatternPrefix,
			String matchPatternPass, String prependDigits, int seq) {
		this.trunkid = trunkid;
		this.matchPatternPrefix = matchPatternPrefix;
		this.matchPatternPass = matchPatternPass;
		this.prependDigits = prependDigits;
		this.seq = seq;
	}

	@Column(name = "trunkid", nullable = false)
	public int getTrunkid() {
		return this.trunkid;
	}

	public void setTrunkid(int trunkid) {
		this.trunkid = trunkid;
	}

	@Column(name = "match_pattern_prefix", nullable = false, length = 50)
	public String getMatchPatternPrefix() {
		return this.matchPatternPrefix;
	}

	public void setMatchPatternPrefix(String matchPatternPrefix) {
		this.matchPatternPrefix = matchPatternPrefix;
	}

	@Id
	@Column(name = "match_pattern_pass", nullable = false, length = 50)
	public String getMatchPatternPass() {
		return this.matchPatternPass;
	}

	public void setMatchPatternPass(String matchPatternPass) {
		this.matchPatternPass = matchPatternPass;
	}

	@Column(name = "prepend_digits", nullable = false, length = 50)
	public String getPrependDigits() {
		return this.prependDigits;
	}

	public void setPrependDigits(String prependDigits) {
		this.prependDigits = prependDigits;
	}

	@Column(name = "seq", nullable = false)
	public int getSeq() {
		return this.seq;
	}

	public void setSeq(int seq) {
		this.seq = seq;
	}
}
