package co.com.tactusoft.crm.model.entities;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.LinkedList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CrmBlockHistory generated by hbm2java
 */
@Entity
@Table(name = "crm_block_history", catalog = "crm_db")
public class CrmBlockHistory implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private CrmPatient crmPatient;
	private CrmUser crmUser;
	private Date demandDate;
	private String description;
	private Date createdDate;
	private List<CrmBlockHistoryDetail> crmBlockHistoryDetails = new LinkedList<CrmBlockHistoryDetail>();

	public CrmBlockHistory() {
	}

	public CrmBlockHistory(CrmPatient crmPatient, CrmUser crmUser,
			Date demandDate, String description, Date createdDate) {
		this.crmPatient = crmPatient;
		this.crmUser = crmUser;
		this.demandDate = demandDate;
		this.description = description;
		this.createdDate = createdDate;
	}

	public CrmBlockHistory(CrmPatient crmPatient, CrmUser crmUser,
			Date demandDate, String description, Date createdDate,
			List<CrmBlockHistoryDetail> crmBlockHistoryDetails) {
		this.crmPatient = crmPatient;
		this.crmUser = crmUser;
		this.demandDate = demandDate;
		this.description = description;
		this.createdDate = createdDate;
		this.crmBlockHistoryDetails = crmBlockHistoryDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_patient", nullable = false)
	public CrmPatient getCrmPatient() {
		return this.crmPatient;
	}

	public void setCrmPatient(CrmPatient crmPatient) {
		this.crmPatient = crmPatient;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_created", nullable = false)
	public CrmUser getCrmUser() {
		return this.crmUser;
	}

	public void setCrmUser(CrmUser crmUser) {
		this.crmUser = crmUser;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "demand_date", nullable = false, length = 10)
	public Date getDemandDate() {
		return this.demandDate;
	}

	public void setDemandDate(Date demandDate) {
		this.demandDate = demandDate;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", nullable = false, length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "crmBlockHistory")
	public List<CrmBlockHistoryDetail> getCrmBlockHistoryDetails() {
		return this.crmBlockHistoryDetails;
	}

	public void setCrmBlockHistoryDetails(
			List<CrmBlockHistoryDetail> crmBlockHistoryDetails) {
		this.crmBlockHistoryDetails = crmBlockHistoryDetails;
	}

}
