package co.com.tactusoft.crm.model.entities;

// Generated 20/06/2012 02:16:10 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CrmConsultation generated by hbm2java
 */
@Entity
@Table(name = "crm_consultation", catalog = "crm_db")
public class CrmConsultation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private BigDecimal idPatient;
	private String review;
	private Date date;
	private BigDecimal idDoctor;

	public CrmConsultation() {
	}

	public CrmConsultation(BigDecimal id, BigDecimal idPatient, String review,
			Date date, BigDecimal idDoctor) {
		this.id = id;
		this.idPatient = idPatient;
		this.review = review;
		this.date = date;
		this.idDoctor = idDoctor;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "id_patient", nullable = false, scale = 0)
	public BigDecimal getIdPatient() {
		return this.idPatient;
	}

	public void setIdPatient(BigDecimal idPatient) {
		this.idPatient = idPatient;
	}

	@Column(name = "review", nullable = false, length = 45)
	public String getReview() {
		return this.review;
	}

	public void setReview(String review) {
		this.review = review;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "id_doctor", nullable = false, scale = 0)
	public BigDecimal getIdDoctor() {
		return this.idDoctor;
	}

	public void setIdDoctor(BigDecimal idDoctor) {
		this.idDoctor = idDoctor;
	}

}
