package co.com.tactusoft.crm.model.entities;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CrmCountry generated by hbm2java
 */
@Entity
@Table(name = "crm_country", catalog = "crm_db", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class CrmCountry implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private String code;
	private String name;
	private String currencyIso;
	private Boolean automatic;
	private String defaultDocType;
	private Integer numPhone;
	private Integer numCell;
	private Set<CrmRegion> crmRegions = new HashSet<CrmRegion>(0);

	public CrmCountry() {
	}

	public CrmCountry(BigDecimal id, String code, String name) {
		this.id = id;
		this.code = code;
		this.name = name;
	}

	public CrmCountry(BigDecimal id, String code, String name,
			String currencyIso, Boolean automatic, String defaultDocType,
			Integer numPhone, Integer numCell, Set<CrmRegion> crmRegions) {
		this.id = id;
		this.code = code;
		this.name = name;
		this.currencyIso = currencyIso;
		this.automatic = automatic;
		this.defaultDocType = defaultDocType;
		this.numPhone = numPhone;
		this.numCell = numCell;
		this.crmRegions = crmRegions;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "code", unique = true, nullable = false, length = 2)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "currency_iso", length = 3)
	public String getCurrencyIso() {
		return this.currencyIso;
	}

	public void setCurrencyIso(String currencyIso) {
		this.currencyIso = currencyIso;
	}

	@Column(name = "automatic")
	public Boolean getAutomatic() {
		return this.automatic;
	}

	public void setAutomatic(Boolean automatic) {
		this.automatic = automatic;
	}

	@Column(name = "default_doc_type", length = 2)
	public String getDefaultDocType() {
		return this.defaultDocType;
	}

	public void setDefaultDocType(String defaultDocType) {
		this.defaultDocType = defaultDocType;
	}

	@Column(name = "num_phone")
	public Integer getNumPhone() {
		return numPhone;
	}

	public void setNumPhone(Integer numPhone) {
		this.numPhone = numPhone;
	}

	@Column(name = "num_cell")
	public Integer getNumCell() {
		return numCell;
	}

	public void setNumCell(Integer numCell) {
		this.numCell = numCell;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmCountry")
	public Set<CrmRegion> getCrmRegions() {
		return this.crmRegions;
	}

	public void setCrmRegions(Set<CrmRegion> crmRegions) {
		this.crmRegions = crmRegions;
	}

	@Override
	public String toString() {
		return this.name;
	}

}
