package co.com.tactusoft.crm.model.entities;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CrmCampaignDetail generated by hbm2java
 */
@Entity
@Table(name = "crm_campaign_detail", catalog = "crm_db")
public class CrmCampaignDetail implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private CrmCampaign crmCampaign;
	private CrmAppointment crmAppointment;
	private CrmUser crmUserByIdUserCreate;
	private CrmUser crmUserByIdUserModified;
	private int idCampaignType;
	private Date callDate;
	private String obs;
	private Date dateCreated;
	private Date dateModified;
	private int status;
	private Set<CrmCampaignTask> crmCampaignTasks = new HashSet<CrmCampaignTask>(
			0);

	public CrmCampaignDetail() {
	}

	public CrmCampaignDetail(CrmCampaign crmCampaign, int idCampaignType,
			Date callDate, int status) {
		this.crmCampaign = crmCampaign;
		this.idCampaignType = idCampaignType;
		this.callDate = callDate;
		this.status = status;
	}

	public CrmCampaignDetail(CrmCampaign crmCampaign,
			CrmAppointment crmAppointment, int idCampaignType, Date callDate,
			String obs, int status, Set<CrmCampaignTask> crmCampaignTasks) {
		this.crmCampaign = crmCampaign;
		this.crmAppointment = crmAppointment;
		this.idCampaignType = idCampaignType;
		this.callDate = callDate;
		this.obs = obs;
		this.status = status;
		this.crmCampaignTasks = crmCampaignTasks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_campaign", nullable = false)
	public CrmCampaign getCrmCampaign() {
		return this.crmCampaign;
	}

	public void setCrmCampaign(CrmCampaign crmCampaign) {
		this.crmCampaign = crmCampaign;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_appointment")
	public CrmAppointment getCrmAppointment() {
		return this.crmAppointment;
	}

	public void setCrmAppointment(CrmAppointment crmAppointment) {
		this.crmAppointment = crmAppointment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_user_modified")
	public CrmUser getCrmUserByIdUserModified() {
		return this.crmUserByIdUserModified;
	}

	public void setCrmUserByIdUserModified(CrmUser crmUserByIdUserModified) {
		this.crmUserByIdUserModified = crmUserByIdUserModified;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_user_created")
	public CrmUser getCrmUserByIdUserCreate() {
		return this.crmUserByIdUserCreate;
	}

	public void setCrmUserByIdUserCreate(CrmUser crmUserByIdUserCreate) {
		this.crmUserByIdUserCreate = crmUserByIdUserCreate;
	}

	@Column(name = "id_campaign_type", nullable = false)
	public int getIdCampaignType() {
		return this.idCampaignType;
	}

	public void setIdCampaignType(int idCampaignType) {
		this.idCampaignType = idCampaignType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "call_date", nullable = false, length = 19)
	public Date getCallDate() {
		return this.callDate;
	}

	public void setCallDate(Date callDate) {
		this.callDate = callDate;
	}

	@Column(name = "obs", length = 65535)
	public String getObs() {
		return obs;
	}

	public void setObs(String obs) {
		this.obs = obs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_created", length = 19)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_modified", length = 19)
	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmCampaignDetail")
	public Set<CrmCampaignTask> getCrmCampaignTasks() {
		return this.crmCampaignTasks;
	}

	public void setCrmCampaignTasks(Set<CrmCampaignTask> crmCampaignTasks) {
		this.crmCampaignTasks = crmCampaignTasks;
	}

}
