package co.com.tactusoft.crm.model.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CrmCampaignType generated by hbm2java
 */
@Entity
@Table(name = "crm_campaign_type", catalog = "crm_db")
public class CrmCampaignType implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private String description;
	private int status;

	public CrmCampaignType() {
	}

	public CrmCampaignType(Integer id) {
		this.id = id;
	}

	public CrmCampaignType(String description, int status) {
		this.description = description;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "description", nullable = false, length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
