package co.com.tactusoft.crm.model.entities;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CrmCampaignTask generated by hbm2java
 */
@Entity
@Table(name = "crm_campaign_task", catalog = "crm_db")
public class CrmCampaignTask implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private CrmCampaignDetail crmCampaignDetail;
	private Date taskDate;

	public CrmCampaignTask() {
	}

	public CrmCampaignTask(CrmCampaignDetail crmCampaignDetail, Date taskDate) {
		this.crmCampaignDetail = crmCampaignDetail;
		this.taskDate = taskDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_campaign_detail", nullable = false)
	public CrmCampaignDetail getCrmCampaignDetail() {
		return this.crmCampaignDetail;
	}

	public void setCrmCampaignDetail(CrmCampaignDetail crmCampaignDetail) {
		this.crmCampaignDetail = crmCampaignDetail;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "task_date", nullable = false, length = 19)
	public Date getTaskDate() {
		return this.taskDate;
	}

	public void setTaskDate(Date taskDate) {
		this.taskDate = taskDate;
	}

}
