package co.com.tactusoft.crm.model.entities;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CrmCity generated by hbm2java
 */
@Entity
@Table(name = "crm_city", catalog = "crm_db", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class CrmCity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private CrmRegion crmRegion;
	private String code;
	private String name;
	private String indicative;

	public CrmCity() {
	}

	public CrmCity(BigDecimal id, String code, String name) {
		this.id = id;
		this.code = code;
		this.name = name;
	}

	public CrmCity(BigDecimal id, CrmRegion crmRegion, String code,
			String name, String indicative) {
		this.id = id;
		this.crmRegion = crmRegion;
		this.code = code;
		this.name = name;
		this.indicative = indicative;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_region")
	public CrmRegion getCrmRegion() {
		return this.crmRegion;
	}

	public void setCrmRegion(CrmRegion crmRegion) {
		this.crmRegion = crmRegion;
	}

	@Column(name = "code", unique = true, nullable = false, length = 10)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "indicative", nullable = true)
	public String getIndicative() {
		return indicative;
	}

	public void setIndicative(String indicative) {
		this.indicative = indicative;
	}

	@Override
	public String toString() {
		return this.name;
	}

}
