package co.com.tactusoft.crm.model.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CrmConsentText generated by hbm2java
 */
@Entity
@Table(name = "crm_consent_text", catalog = "crm_db")
public class CrmConsentText implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long id;
	private CrmConsent crmConsent;
	private String consentText;

	public CrmConsentText() {
	}

	public CrmConsentText(CrmConsent crmConsent, String consentText) {
		this.crmConsent = crmConsent;
		this.consentText = consentText;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_consent", nullable = false)
	public CrmConsent getCrmConsent() {
		return this.crmConsent;
	}

	public void setCrmConsent(CrmConsent crmConsent) {
		this.crmConsent = crmConsent;
	}

	@Column(name = "consent_text", nullable = false, length = 65535, columnDefinition = "TEXT")
	public String getConsentText() {
		return this.consentText;
	}

	public void setConsentText(String consentText) {
		this.consentText = consentText;
	}

}
