package co.com.tactusoft.crm.model.entities;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CrmConsent generated by hbm2java
 */
@Entity
@Table(name = "crm_consent", catalog = "crm_db")
public class CrmConsent implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long id;
	private CrmPatient crmPatient;
	private CrmAppointment crmAppointment;
	private Date dateInformed;
	private byte[] consentFile;
	private String consentType;
	private String fileType;

	public CrmConsent() {
	}

	public CrmConsent(CrmPatient crmPatient, Date dateInformed,
			byte[] consentFile, String fileType) {
		this.crmPatient = crmPatient;
		this.dateInformed = dateInformed;
		this.consentFile = consentFile;
		this.fileType = fileType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_patient", nullable = false)
	public CrmPatient getCrmPatient() {
		return this.crmPatient;
	}

	public void setCrmPatient(CrmPatient crmPatient) {
		this.crmPatient = crmPatient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_appointment", nullable = false)
	public CrmAppointment getCrmAppointment() {
		return crmAppointment;
	}

	public void setCrmAppointment(CrmAppointment crmAppointment) {
		this.crmAppointment = crmAppointment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_informed", nullable = false, length = 19)
	public Date getDateInformed() {
		return this.dateInformed;
	}

	public void setDateInformed(Date dateInformed) {
		this.dateInformed = dateInformed;
	}

	@Column(name = "consent_file", nullable = false)
	public byte[] getConsentFile() {
		return this.consentFile;
	}

	public void setConsentFile(byte[] consentFile) {
		this.consentFile = consentFile;
	}

	@Column(name = "consent_type", nullable = false)
	public String getConsentType() {
		return consentType;
	}

	public void setConsentType(String consentType) {
		this.consentType = consentType;
	}

	@Column(name = "file_type", nullable = false)
	public String getFileType() {
		return fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

}
