package co.com.tactusoft.crm.model.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CrmCustodyBelongings generated by hbm2java
 */
@Entity
@Table(name = "crm_custody_belongings", catalog = "crm_db")
public class CrmCustodyBelongings implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long id;
	private CrmAppointment crmAppointment;
	private String belongings;

	public CrmCustodyBelongings() {
	}

	public CrmCustodyBelongings(CrmAppointment crmAppointment, String belongings) {
		this.crmAppointment = crmAppointment;
		this.belongings = belongings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_appointment", nullable = false)
	public CrmAppointment getCrmAppointment() {
		return this.crmAppointment;
	}

	public void setCrmAppointment(CrmAppointment crmAppointment) {
		this.crmAppointment = crmAppointment;
	}

	@Column(name = "belongings", nullable = false, length = 1000)
	public String getBelongings() {
		return this.belongings;
	}

	public void setBelongings(String belongings) {
		this.belongings = belongings;
	}

}
