package co.com.tactusoft.crm.model.entities;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CrmCallType generated by hbm2java
 */
@Entity
@Table(name = "crm_call_type", catalog = "crm_db")
public class CrmCallType implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String code;
	private String description;
	private String callType;
	private int status;
	private Set<CrmCallTypeDetail> crmCallTypeDetails = new HashSet<CrmCallTypeDetail>(
			0);

	public CrmCallType() {
	}

	public CrmCallType(String code, String description, String callType,
			int status) {
		this.code = code;
		this.description = description;
		this.callType = callType;
		this.status = status;
	}

	public CrmCallType(String code, String description, String callType,
			int status, Set<CrmCallTypeDetail> crmCallTypeDetails) {
		this.code = code;
		this.description = description;
		this.callType = callType;
		this.status = status;
		this.crmCallTypeDetails = crmCallTypeDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "code", nullable = false)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "call_type", nullable = false, length = 30)
	public String getCallType() {
		return this.callType;
	}

	public void setCallType(String callType) {
		this.callType = callType;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmCallType")
	public Set<CrmCallTypeDetail> getCrmCallTypeDetails() {
		return this.crmCallTypeDetails;
	}

	public void setCrmCallTypeDetails(Set<CrmCallTypeDetail> crmCallTypeDetails) {
		this.crmCallTypeDetails = crmCallTypeDetails;
	}

}
