package co.com.tactusoft.crm.model.entities;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CrmDepartment generated by hbm2java
 */
@Entity
@Table(name = "crm_department", catalog = "crm_db", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class CrmDepartment implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private String code;
	private String name;
	private int state;
	private Set<CrmUser> crmUsers = new HashSet<CrmUser>(0);

	public CrmDepartment() {
	}

	public CrmDepartment(BigDecimal id, String code, String name, int state) {
		this.id = id;
		this.code = code;
		this.name = name;
		this.state = state;
	}

	public CrmDepartment(BigDecimal id, String code, String name, int state,
			Set<CrmUser> crmUsers) {
		this.id = id;
		this.code = code;
		this.name = name;
		this.state = state;
		this.crmUsers = crmUsers;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "code", unique = true, nullable = false, length = 45)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmDepartment")
	public Set<CrmUser> getCrmUsers() {
		return this.crmUsers;
	}

	public void setCrmUsers(Set<CrmUser> crmUsers) {
		this.crmUsers = crmUsers;
	}

}
