package co.com.tactusoft.crm.model.entities;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CrmDiagnosis generated by hbm2java
 */
@Entity
@Table(name = "crm_diagnosis", catalog = "crm_db", uniqueConstraints = @UniqueConstraint(columnNames = {
		"id_appointment", "id_cie" }))
public class CrmDiagnosis implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private CrmAppointment crmAppointment;
	private CrmCie crmCie;
	private String posology;
	private BigDecimal idDiagnosisType;

	public CrmDiagnosis() {
	}

	public CrmDiagnosis(BigDecimal id, CrmAppointment crmAppointment,
			CrmCie crmCie) {
		this.id = id;
		this.crmAppointment = crmAppointment;
		this.crmCie = crmCie;
	}

	public CrmDiagnosis(BigDecimal id, CrmAppointment crmAppointment,
			CrmCie crmCie, String posology) {
		this.id = id;
		this.crmAppointment = crmAppointment;
		this.crmCie = crmCie;
		this.posology = posology;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_appointment", nullable = false)
	public CrmAppointment getCrmAppointment() {
		return this.crmAppointment;
	}

	public void setCrmAppointment(CrmAppointment crmAppointment) {
		this.crmAppointment = crmAppointment;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_cie", nullable = false)
	public CrmCie getCrmCie() {
		return this.crmCie;
	}

	public void setCrmCie(CrmCie crmCie) {
		this.crmCie = crmCie;
	}

	@Column(name = "posology", length = 65535)
	public String getPosology() {
		return this.posology;
	}

	public void setPosology(String posology) {
		this.posology = posology;
	}

	@Column(name = "id_diagnosis_type")
	public BigDecimal getIdDiagnosisType() {
		return idDiagnosisType;
	}

	public void setIdDiagnosisType(BigDecimal idDiagnosisType) {
		this.idDiagnosisType = idDiagnosisType;
	}

}
