package co.com.tactusoft.crm.model.entities;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CrmGuideline generated by hbm2java
 */
@Entity
@Table(name = "crm_guideline", catalog = "crm_db")
public class CrmGuideline implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private String descMedia;
	private BigDecimal idPublicity;
	private String phone;
	private String guideline;
	private BigDecimal idProfile;
	private BigDecimal idCountry;
	private String libretto;

	public CrmGuideline() {
	}

	public CrmGuideline(BigDecimal id, String descMedia) {
		this.id = id;
		this.descMedia = descMedia;
	}

	public CrmGuideline(BigDecimal id, String descMedia,
			BigDecimal idPublicity, String phone, String guideline) {
		this.id = id;
		this.descMedia = descMedia;
		this.idPublicity = idPublicity;
		this.phone = phone;
		this.guideline = guideline;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "desc_media", nullable = false, length = 1000)
	public String getDescMedia() {
		return this.descMedia;
	}

	public void setDescMedia(String descMedia) {
		this.descMedia = descMedia;
	}

	@Column(name = "id_publicity", scale = 0)
	public BigDecimal getIdPublicity() {
		return this.idPublicity;
	}

	public void setIdPublicity(BigDecimal idPublicity) {
		this.idPublicity = idPublicity;
	}

	@Column(name = "phone", length = 45)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "guideline", length = 1000)
	public String getGuideline() {
		return this.guideline;
	}

	public void setGuideline(String guideline) {
		this.guideline = guideline;
	}

	@Column(name = "id_profile", scale = 0)
	public BigDecimal getIdProfile() {
		return idProfile;
	}

	public void setIdProfile(BigDecimal idProfile) {
		this.idProfile = idProfile;
	}

	@Column(name = "id_country", scale = 0)
	public BigDecimal getIdCountry() {
		return idCountry;
	}

	public void setIdCountry(BigDecimal idCountry) {
		this.idCountry = idCountry;
	}

	@Column(name = "libretto")
	public String getLibretto() {
		return libretto;
	}

	public void setLibretto(String libretto) {
		this.libretto = libretto;
	}

}
