package co.com.tactusoft.crm.model.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import co.com.tactusoft.crm.model.util.EntityId;

/**
 * CrmHistoryIridology generated by hbm2java
 */
@Entity
@Table(name = "crm_history_iridology", catalog = "crm_db")
public class CrmHistoryIridology implements java.io.Serializable, EntityId {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private CrmAppointment crmAppointment;
	private String leftObs;
	private byte[] leftEye;
	private String leftExtension;
	private String rightObs;
	private byte[] rightEye;
	private String rightExtension;

	public CrmHistoryIridology() {
	}

	public CrmHistoryIridology(CrmAppointment crmAppointment, String leftObs,
			byte[] leftEye, String leftExtension, String rightObs,
			byte[] rightEye, String rightExtension) {
		this.crmAppointment = crmAppointment;
		this.leftObs = leftObs;
		this.leftEye = leftEye;
		this.leftExtension = leftExtension;
		this.rightObs = rightObs;
		this.rightEye = rightEye;
		this.rightExtension = rightExtension;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	@Override
	public Integer getId() {
		return this.id;
	}

	@Override
	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_appointment", nullable = false)
	public CrmAppointment getCrmAppointment() {
		return this.crmAppointment;
	}

	public void setCrmAppointment(CrmAppointment crmAppointment) {
		this.crmAppointment = crmAppointment;
	}

	@Column(name = "left_obs", nullable = false, length = 65535)
	public String getLeftObs() {
		return leftObs;
	}

	public void setLeftObs(String leftObs) {
		this.leftObs = leftObs;
	}

	@Column(name = "left_eye", nullable = false)
	public byte[] getLeftEye() {
		return leftEye;
	}

	public void setLeftEye(byte[] leftEye) {
		this.leftEye = leftEye;
	}

	@Column(name = "left_extension", nullable = false, length = 4)
	public String getLeftExtension() {
		return leftExtension;
	}

	public void setLeftExtension(String leftExtension) {
		this.leftExtension = leftExtension;
	}

	@Column(name = "right_obs", nullable = false, length = 65535)
	public String getRightObs() {
		return rightObs;
	}

	public void setRightObs(String rightObs) {
		this.rightObs = rightObs;
	}

	@Column(name = "right_eye", nullable = false)
	public byte[] getRightEye() {
		return rightEye;
	}

	public void setRightEye(byte[] rightEye) {
		this.rightEye = rightEye;
	}

	@Column(name = "right_extension", nullable = false, length = 4)
	public String getRightExtension() {
		return rightExtension;
	}

	public void setRightExtension(String rightExtension) {
		this.rightExtension = rightExtension;
	}

}
