package co.com.tactusoft.crm.model.entities;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CrmHolidayBranch generated by hbm2java
 */
@Entity
@Table(name = "crm_holiday_branch", catalog = "crm_db", uniqueConstraints = @UniqueConstraint(columnNames = {
		"id_holiday", "id_branch" }))
public class CrmHolidayBranch implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private CrmHoliday crmHoliday;
	private CrmBranch crmBranch;

	public CrmHolidayBranch() {
	}

	public CrmHolidayBranch(BigDecimal id, CrmHoliday crmHoliday,
			CrmBranch crmBranch) {
		this.id = id;
		this.crmHoliday = crmHoliday;
		this.crmBranch = crmBranch;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_holiday", nullable = false)
	public CrmHoliday getCrmHoliday() {
		return this.crmHoliday;
	}

	public void setCrmHoliday(CrmHoliday crmHoliday) {
		this.crmHoliday = crmHoliday;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_branch", nullable = false)
	public CrmBranch getCrmBranch() {
		return this.crmBranch;
	}

	public void setCrmBranch(CrmBranch crmBranch) {
		this.crmBranch = crmBranch;
	}

}
