package co.com.tactusoft.crm.model.entities;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * CrmHoliday generated by hbm2java
 */
@Entity
@Table(name = "crm_holiday", catalog = "crm_db", uniqueConstraints = @UniqueConstraint(columnNames = "holiday"))
public class CrmHoliday implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private String description;
	private Date holiday;
	private Set<CrmHolidayBranch> crmHolidayBranchs = new HashSet<CrmHolidayBranch>(
			0);

	public CrmHoliday() {
	}

	public CrmHoliday(BigDecimal id, String description, Date holiday) {
		this.id = id;
		this.description = description;
		this.holiday = holiday;
	}

	public CrmHoliday(BigDecimal id, String description, Date holiday,
			Set<CrmHolidayBranch> crmHolidayBranchs) {
		this.id = id;
		this.description = description;
		this.holiday = holiday;
		this.crmHolidayBranchs = crmHolidayBranchs;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "description", nullable = false, length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "holiday", unique = true, nullable = false, length = 10)
	public Date getHoliday() {
		return this.holiday;
	}

	public void setHoliday(Date holiday) {
		this.holiday = holiday;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmHoliday")
	public Set<CrmHolidayBranch> getCrmHolidayBranchs() {
		return this.crmHolidayBranchs;
	}

	public void setCrmHolidayBranchs(Set<CrmHolidayBranch> crmHolidayBranchs) {
		this.crmHolidayBranchs = crmHolidayBranchs;
	}

}
