package co.com.tactusoft.crm.model.entities;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CrmCountry generated by hbm2java
 */
@Entity
@Table(name = "crm_infusion_tag", catalog = "crm_db", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class CrmInfusionTag implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer code;
	private String description;
	private Integer orderby;
	private Integer status;

	public CrmInfusionTag() {
	}

	public CrmInfusionTag(Integer id) {
		super();
		this.id = id;
	}

	public CrmInfusionTag(Integer id, Integer code, String description,
			Integer orderby, Integer status) {
		super();
		this.id = id;
		this.code = code;
		this.description = description;
		this.orderby = orderby;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "code", unique = true, nullable = false)
	public Integer getCode() {
		return this.code;
	}

	public void setCode(Integer code) {
		this.code = code;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "orderby", nullable = false)
	public Integer getOrderby() {
		return orderby;
	}

	public void setOrderby(Integer orderby) {
		this.orderby = orderby;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
