package co.com.tactusoft.crm.model.entities;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CrmLog generated by hbm2java
 */
@Entity
@Table(name = "crm_log", catalog = "crm_db")
public class CrmLog implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private String logType;
	private Date logDate;
	private Set<CrmCampaign> crmCampaigns = new HashSet<CrmCampaign>(0);
	private Set<CrmLogDetail> crmLogDetails = new HashSet<CrmLogDetail>(0);

	public CrmLog() {
	}

	public CrmLog(Integer id) {
		this.id = id;
	}

	public CrmLog(String logType, Date logDate) {
		this.logType = logType;
		this.logDate = logDate;
	}

	public CrmLog(String logType, Date logDate, Set<CrmCampaign> crmCampaigns,
			Set<CrmLogDetail> crmLogDetails) {
		this.logType = logType;
		this.logDate = logDate;
		this.crmCampaigns = crmCampaigns;
		this.crmLogDetails = crmLogDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "log_type", nullable = false, length = 45)
	public String getLogType() {
		return this.logType;
	}

	public void setLogType(String logType) {
		this.logType = logType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "log_date", nullable = false, length = 19)
	public Date getLogDate() {
		return this.logDate;
	}

	public void setLogDate(Date logDate) {
		this.logDate = logDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmLog")
	public Set<CrmCampaign> getCrmCampaigns() {
		return this.crmCampaigns;
	}

	public void setCrmCampaigns(Set<CrmCampaign> crmCampaigns) {
		this.crmCampaigns = crmCampaigns;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmLog")
	public Set<CrmLogDetail> getCrmLogDetails() {
		return this.crmLogDetails;
	}

	public void setCrmLogDetails(Set<CrmLogDetail> crmLogDetails) {
		this.crmLogDetails = crmLogDetails;
	}

}
