package co.com.tactusoft.crm.model.entities;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CrmLogDetail generated by hbm2java
 */
@Entity
@Table(name = "crm_log_detail", catalog = "crm_db")
public class CrmLogDetail implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	private Integer id;
	private CrmLog crmLog;
	private String message;
	private Date logDate;

	public CrmLogDetail() {
	}

	public CrmLogDetail(CrmLog crmLog, String message, Date logDate) {
		this.crmLog = crmLog;
		this.message = message;
		this.logDate = logDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_log", nullable = false)
	public CrmLog getCrmLog() {
		return this.crmLog;
	}

	public void setCrmLog(CrmLog crmLog) {
		this.crmLog = crmLog;
	}

	@Column(name = "message", nullable = false, length = 65535)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "log_date", nullable = false, length = 19)
	public Date getLogDate() {
		return this.logDate;
	}

	public void setLogDate(Date logDate) {
		this.logDate = logDate;
	}

}
