package co.com.tactusoft.crm.model.entities;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CrmMembershipReport generated by hbm2java
 */
@Entity
@Table(name = "crm_membership_report", catalog = "crm_db")
public class CrmMembershipReport implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private CrmUser crmUser;
	private CrmBranch crmBranch;
	private Date reportDate;
	private int respondents;
	private int memberships;
	private Date createdDate;
	private String promoter;
	private String obs;

	public CrmMembershipReport() {
	}

	public CrmMembershipReport(CrmUser crmUser, CrmBranch crmBranch,
			Date reportDate, int respondents, int memberships, Date createdDate,String promoter,String obs) {
		this.crmUser = crmUser;
		this.crmBranch = crmBranch;
		this.reportDate = reportDate;
		this.respondents = respondents;
		this.memberships = memberships;
		this.createdDate = createdDate;
		this.promoter = promoter;
		this.obs = obs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_user", nullable = false)
	public CrmUser getCrmUser() {
		return this.crmUser;
	}

	public void setCrmUser(CrmUser crmUser) {
		this.crmUser = crmUser;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_branch", nullable = false)
	public CrmBranch getCrmBranch() {
		return this.crmBranch;
	}

	public void setCrmBranch(CrmBranch crmBranch) {
		this.crmBranch = crmBranch;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "report_date", nullable = false, length = 10)
	public Date getReportDate() {
		return this.reportDate;
	}

	public void setReportDate(Date reportDate) {
		this.reportDate = reportDate;
	}

	@Column(name = "respondents", nullable = false)
	public int getRespondents() {
		return this.respondents;
	}

	public void setRespondents(int respondents) {
		this.respondents = respondents;
	}

	@Column(name = "memberships", nullable = false)
	public int getMemberships() {
		return this.memberships;
	}

	public void setMemberships(int memberships) {
		this.memberships = memberships;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "promoter", nullable = false, length = 255)
	public String getPromoter() {
		return promoter;
	}

	public void setPromoter(String promoter) {
		this.promoter = promoter;
	}

	@Column(name = "obs", nullable = false, length = 65535)
	public String getObs() {
		return obs;
	}

	public void setObs(String obs) {
		this.obs = obs;
	}

}
