package co.com.tactusoft.crm.model.entities;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * CrmMarketingActivity generated by hbm2java
 */
@Entity
@Table(name = "crm_marketing_activity", catalog = "crm_db", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class CrmMarketingActivity implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private CrmCity crmCity;
	private String name;
	private Date startDate;
	private Date finishDate;
	private String template;
	private int status;

	public CrmMarketingActivity() {
	}
	
	public CrmMarketingActivity(Integer id) {
		this.id = id;
	}

	public CrmMarketingActivity(CrmCity crmCity, String name, String template) {
		this.crmCity = crmCity;
		this.name = name;
		this.template = template;
	}

	public CrmMarketingActivity(CrmCity crmCity, String name, Date startDate,
			Date finishDate, String template, int status) {
		this.crmCity = crmCity;
		this.name = name;
		this.startDate = startDate;
		this.finishDate = finishDate;
		this.template = template;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_city", nullable = false)
	public CrmCity getCrmCity() {
		return this.crmCity;
	}

	public void setCrmCity(CrmCity crmCity) {
		this.crmCity = crmCity;
	}

	@Column(name = "name", unique = true, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "finish_date", length = 10)
	public Date getFinishDate() {
		return this.finishDate;
	}

	public void setFinishDate(Date finishDate) {
		this.finishDate = finishDate;
	}

	@Column(name = "template", nullable = false, length = 65535)
	public String getTemplate() {
		return this.template;
	}

	public void setTemplate(String template) {
		this.template = template;
	}

	@Column(name = "status")
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
