package co.com.tactusoft.crm.model.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CrmOdontologyPeriodontal generated by hbm2java
 */
@Entity
@Table(name = "crm_odontology_periodontal", catalog = "crm_db")
public class CrmOdontologyPeriodontal implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private CrmAppointment crmAppointment;
	private Integer gingivitis;
	private Integer periodontitis;
	private Integer mobility;
	private Integer bagTeeth;
	private Integer gingivalRecession;
	private Integer plaqueIndex;
	private String obs;

	public CrmOdontologyPeriodontal() {
	}

	public CrmOdontologyPeriodontal(CrmAppointment crmAppointment) {
		this.crmAppointment = crmAppointment;
	}

	public CrmOdontologyPeriodontal(CrmAppointment crmAppointment,
			Integer gingivitis, Integer periodontitis, Integer mobility,
			Integer bagTeeth, Integer gingivalRecession, Integer plaqueIndex,
			String obs) {
		this.crmAppointment = crmAppointment;
		this.gingivitis = gingivitis;
		this.periodontitis = periodontitis;
		this.mobility = mobility;
		this.bagTeeth = bagTeeth;
		this.gingivalRecession = gingivalRecession;
		this.plaqueIndex = plaqueIndex;
		this.obs = obs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_appointment", nullable = false)
	public CrmAppointment getCrmAppointment() {
		return this.crmAppointment;
	}

	public void setCrmAppointment(CrmAppointment crmAppointment) {
		this.crmAppointment = crmAppointment;
	}

	@Column(name = "gingivitis")
	public Integer getGingivitis() {
		return this.gingivitis;
	}

	public void setGingivitis(Integer gingivitis) {
		this.gingivitis = gingivitis;
	}

	@Column(name = "periodontitis")
	public Integer getPeriodontitis() {
		return this.periodontitis;
	}

	public void setPeriodontitis(Integer periodontitis) {
		this.periodontitis = periodontitis;
	}

	@Column(name = "mobility")
	public Integer getMobility() {
		return this.mobility;
	}

	public void setMobility(Integer mobility) {
		this.mobility = mobility;
	}

	@Column(name = "bag_teeth")
	public Integer getBagTeeth() {
		return this.bagTeeth;
	}

	public void setBagTeeth(Integer bagTeeth) {
		this.bagTeeth = bagTeeth;
	}

	@Column(name = "gingival_recession")
	public Integer getGingivalRecession() {
		return this.gingivalRecession;
	}

	public void setGingivalRecession(Integer gingivalRecession) {
		this.gingivalRecession = gingivalRecession;
	}

	@Column(name = "plaque_index")
	public Integer getPlaqueIndex() {
		return this.plaqueIndex;
	}

	public void setPlaqueIndex(Integer plaqueIndex) {
		this.plaqueIndex = plaqueIndex;
	}

	@Column(name = "obs", length = 65535)
	public String getObs() {
		return this.obs;
	}

	public void setObs(String obs) {
		this.obs = obs;
	}

}
