package co.com.tactusoft.crm.model.entities;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import co.com.tactusoft.crm.model.entities.CrmAppointment;


/**
 * CrmOdontologyOdontogram generated by hbm2java
 */
@Entity
@Table(name = "crm_odontology_odontogram", catalog = "crm_db")
public class CrmOdontologyOdontogram implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private CrmAppointment crmAppointment;
	private CrmOdotogramProcedure crmOdotogramProcedure;
	private String tooth;

	public CrmOdontologyOdontogram() {
	}

	public CrmOdontologyOdontogram(CrmAppointment crmAppointment,
			CrmOdotogramProcedure crmOdotogramProcedure, String tooth) {
		this.crmAppointment = crmAppointment;
		this.crmOdotogramProcedure = crmOdotogramProcedure;
		this.tooth = tooth;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_appointment")
	public CrmAppointment getCrmAppointment() {
		return this.crmAppointment;
	}

	public void setCrmAppointment(CrmAppointment crmAppointment) {
		this.crmAppointment = crmAppointment;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_procedure")
	public CrmOdotogramProcedure getCrmOdotogramProcedure() {
		return crmOdotogramProcedure;
	}

	public void setCrmOdotogramProcedure(
			CrmOdotogramProcedure crmOdotogramProcedure) {
		this.crmOdotogramProcedure = crmOdotogramProcedure;
	}

	@Column(name = "tooth", nullable = false, length = 3)
	public String getTooth() {
		return this.tooth;
	}

	public void setTooth(String tooth) {
		this.tooth = tooth;
	}

}
