package co.com.tactusoft.crm.model.entities;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CrmParameter generated by hbm2java
 */
@Entity
@Table(name = "crm_parameter", catalog = "crm_db", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class CrmParameter implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private String code;
	private String description;
	private String textValue;
	private BigDecimal numberValue;
	private String byGroup;

	public CrmParameter() {
	}

	public CrmParameter(BigDecimal id) {
		this.id = id;
	}

	public CrmParameter(BigDecimal id, String code, String description,
			String textValue, BigDecimal numberValue, String byGroup) {
		this.id = id;
		this.code = code;
		this.description = description;
		this.textValue = textValue;
		this.numberValue = numberValue;
		this.byGroup = byGroup;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "code", unique = true, length = 45)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "description", length = 255)
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "text_value", length = 45)
	public String getTextValue() {
		return this.textValue;
	}

	public void setTextValue(String textValue) {
		this.textValue = textValue;
	}

	@Column(name = "number_value", scale = 3)
	public BigDecimal getNumberValue() {
		return this.numberValue;
	}

	public void setNumberValue(BigDecimal numberValue) {
		this.numberValue = numberValue;
	}

	@Column(name = "group_by", length = 45)
	public String getByGroup() {
		return byGroup;
	}

	public void setByGroup(String byGroup) {
		this.byGroup = byGroup;
	}

}
