package co.com.tactusoft.crm.model.entities;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CrmPatientTicket generated by hbm2java
 */
@Entity
@Table(name = "crm_patient_ticket", catalog = "crm_db", uniqueConstraints = @UniqueConstraint(columnNames = "ticket"))
public class CrmPatientTicket implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private CrmPatient crmPatient;
	private CrmTicket crmTicket;
	private String ticket;

	public CrmPatientTicket() {
	}

	public CrmPatientTicket(CrmPatient crmPatient, CrmTicket crmTicket,
			String ticket) {
		this.crmPatient = crmPatient;
		this.crmTicket = crmTicket;
		this.ticket = ticket;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_patient", nullable = false)
	public CrmPatient getCrmPatient() {
		return this.crmPatient;
	}

	public void setCrmPatient(CrmPatient crmPatient) {
		this.crmPatient = crmPatient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ticket", nullable = false)
	public CrmTicket getCrmTicket() {
		return crmTicket;
	}

	public void setCrmTicket(CrmTicket crmTicket) {
		this.crmTicket = crmTicket;
	}

	@Column(name = "ticket", unique = true, nullable = false, length = 45)
	public String getTicket() {
		return this.ticket;
	}

	public void setTicket(String ticket) {
		this.ticket = ticket;
	}

}
