package co.com.tactusoft.crm.model.entities;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CrmProcedureBranch generated by hbm2java
 */
@Entity
@Table(name = "crm_procedure_branch", catalog = "crm_db")
public class CrmProcedureBranch implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private CrmProcedureDetail crmProcedure;
	private CrmBranch crmBranch;

	public CrmProcedureBranch() {
	}

	public CrmProcedureBranch(BigDecimal id, CrmProcedureDetail crmProcedure,
			CrmBranch crmBranch) {
		this.id = id;
		this.crmProcedure = crmProcedure;
		this.crmBranch = crmBranch;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_procedure", nullable = false)
	public CrmProcedureDetail getCrmProcedure() {
		return this.crmProcedure;
	}

	public void setCrmProcedure(CrmProcedureDetail crmProcedure) {
		this.crmProcedure = crmProcedure;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_branch", nullable = false)
	public CrmBranch getCrmBranch() {
		return this.crmBranch;
	}

	public void setCrmBranch(CrmBranch crmBranch) {
		this.crmBranch = crmBranch;
	}

}
