package co.com.tactusoft.crm.model.entities;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CrmPageRole generated by hbm2java
 */
@Entity
@Table(name = "crm_page_role", catalog = "crm_db", uniqueConstraints = @UniqueConstraint(columnNames = {
		"id_page", "id_role" }))
public class CrmPageRole implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private CrmRole crmRole;
	private CrmPage crmPage;

	public CrmPageRole() {
	}

	public CrmPageRole(BigDecimal id, CrmRole crmRole, CrmPage crmPage) {
		this.id = id;
		this.crmRole = crmRole;
		this.crmPage = crmPage;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_role", nullable = false)
	public CrmRole getCrmRole() {
		return this.crmRole;
	}

	public void setCrmRole(CrmRole crmRole) {
		this.crmRole = crmRole;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_page", nullable = false)
	public CrmPage getCrmPage() {
		return this.crmPage;
	}

	public void setCrmPage(CrmPage crmPage) {
		this.crmPage = crmPage;
	}

}
