package co.com.tactusoft.crm.model.entities;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CrmRegion generated by hbm2java
 */
@Entity
@Table(name = "crm_region", catalog = "crm_db", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class CrmRegion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private CrmCountry crmCountry;
	private String code;
	private String name;
	private Set<CrmCity> crmCities = new HashSet<CrmCity>(0);

	public CrmRegion() {
	}

	public CrmRegion(BigDecimal id, CrmCountry crmCountry, String code,
			String name) {
		this.id = id;
		this.crmCountry = crmCountry;
		this.code = code;
		this.name = name;
	}

	public CrmRegion(BigDecimal id, CrmCountry crmCountry, String code,
			String name, Set<CrmCity> crmCities) {
		this.id = id;
		this.crmCountry = crmCountry;
		this.code = code;
		this.name = name;
		this.crmCities = crmCities;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_country", nullable = false)
	public CrmCountry getCrmCountry() {
		return this.crmCountry;
	}

	public void setCrmCountry(CrmCountry crmCountry) {
		this.crmCountry = crmCountry;
	}

	@Column(name = "code", unique = true, nullable = false, length = 3)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmRegion")
	@OrderBy("name")
	public Set<CrmCity> getCrmCities() {
		return this.crmCities;
	}

	public void setCrmCities(Set<CrmCity> crmCities) {
		this.crmCities = crmCities;
	}
	
	@Override
	public String toString() {
		return this.name;
	}

}
