package co.com.tactusoft.crm.model.entities;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CrmRecall generated by hbm2java
 */
@Entity
@Table(name = "crm_recall", catalog = "crm_db")
public class CrmRecall implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private CrmRecall crmRecall;
	private Integer idTaskType;
	private String description;
	private String task;
	private String guideline;
	private Integer numDays;
	private Integer occurrences;
	private Integer numDaysAux;
	private Integer maximum;
	private List<CrmRecall> crmRecalls = new ArrayList<CrmRecall>();

	public CrmRecall() {
	}

	public CrmRecall(int idTaskType, String description, int numDays,
			int occurrences, int numDaysAux, int maximum) {
		this.idTaskType = idTaskType;
		this.description = description;
		this.numDays = numDays;
		this.occurrences = occurrences;
		this.numDaysAux = numDaysAux;
		this.maximum = maximum;
	}

	public CrmRecall(CrmRecall crmRecall, int idTaskType, String description,
			String task, String guideline, int numDays, int occurrences,
			int numDaysAux, int maximum, List<CrmRecall> crmRecalls) {
		this.crmRecall = crmRecall;
		this.idTaskType = idTaskType;
		this.description = description;
		this.task = task;
		this.guideline = guideline;
		this.numDays = numDays;
		this.occurrences = occurrences;
		this.numDaysAux = numDaysAux;
		this.maximum = maximum;
		this.crmRecalls = crmRecalls;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_parent")
	public CrmRecall getCrmRecall() {
		return this.crmRecall;
	}

	public void setCrmRecall(CrmRecall crmRecall) {
		this.crmRecall = crmRecall;
	}

	@Column(name = "id_task_type", nullable = false)
	public int getIdTaskType() {
		return this.idTaskType;
	}

	public void setIdTaskType(int idTaskType) {
		this.idTaskType = idTaskType;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "task", length = 45)
	public String getTask() {
		return this.task;
	}

	public void setTask(String task) {
		this.task = task;
	}

	@Column(name = "guideline", length = 65535)
	public String getGuideline() {
		return this.guideline;
	}

	public void setGuideline(String guideline) {
		this.guideline = guideline;
	}

	@Column(name = "num_days", nullable = false)
	public int getNumDays() {
		return this.numDays;
	}

	public void setNumDays(int numDays) {
		this.numDays = numDays;
	}

	@Column(name = "occurrences", nullable = false)
	public int getOccurrences() {
		return this.occurrences;
	}

	public void setOccurrences(int occurrences) {
		this.occurrences = occurrences;
	}

	@Column(name = "num_days_aux", nullable = false)
	public int getNumDaysAux() {
		return this.numDaysAux;
	}

	public void setNumDaysAux(int numDaysAux) {
		this.numDaysAux = numDaysAux;
	}

	@Column(name = "maximum", nullable = false)
	public int getMaximum() {
		return this.maximum;
	}

	public void setMaximum(int maximum) {
		this.maximum = maximum;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmRecall")
	public List<CrmRecall> getCrmRecalls() {
		return this.crmRecalls;
	}

	public void setCrmRecalls(List<CrmRecall> crmRecalls) {
		this.crmRecalls = crmRecalls;
	}

}
