package co.com.tactusoft.crm.model.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CrmRepMedication generated by hbm2java
 */
@Entity
@Table(name = "crm_rep_medication", catalog = "crm_db")
public class CrmRepMedication implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private CrmRepSymptom crmRepSymptom;
	private String code;
	private String description;
	private byte value;

	public CrmRepMedication() {
	}

	public CrmRepMedication(CrmRepSymptom crmRepSymptom, String code,
			String description, byte value) {
		this.crmRepSymptom = crmRepSymptom;
		this.code = code;
		this.description = description;
		this.value = value;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_symptom", nullable = false)
	public CrmRepSymptom getCrmRepSymptom() {
		return this.crmRepSymptom;
	}

	public void setCrmRepSymptom(CrmRepSymptom crmRepSymptom) {
		this.crmRepSymptom = crmRepSymptom;
	}

	@Column(name = "code", nullable = false, length = 15)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "description", nullable = false, length = 40)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "value", nullable = false)
	public byte getValue() {
		return this.value;
	}

	public void setValue(byte value) {
		this.value = value;
	}

}
