package co.com.tactusoft.crm.model.entities;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CrmSaleOrder generated by hbm2java
 */
@Entity
@Table(name = "crm_sale_order", catalog = "crm_db")
public class CrmSaleOrder implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private CrmPatient crmPatient;
	private CrmUser crmUser;
	private CrmProfile crmProfile;
	private Date saleDate;
	private String salesOrg;
	private String distrChan;
	private String methodPayment;
	private String paymentTerm;
	private String salesGroup;
	private String orderType;
	private Date creationDate;
	private Set<CrmSaleOrderDetail> crmSaleOrderDetails = new HashSet<CrmSaleOrderDetail>(
			0);

	public CrmSaleOrder() {
	}

	public CrmSaleOrder(CrmPatient crmPatient, CrmUser crmUser,
			CrmProfile crmProfile, Date saleDate, String salesOrg,
			String distrChan, String methodPayment, String paymentTerm,
			String salesGroup, String orderType, Date creationDate) {
		this.crmPatient = crmPatient;
		this.crmUser = crmUser;
		this.crmProfile = crmProfile;
		this.saleDate = saleDate;
		this.salesOrg = salesOrg;
		this.distrChan = distrChan;
		this.methodPayment = methodPayment;
		this.paymentTerm = paymentTerm;
		this.salesGroup = salesGroup;
		this.orderType = orderType;
		this.creationDate = creationDate;
	}

	public CrmSaleOrder(CrmPatient crmPatient, CrmUser crmUser,
			CrmProfile crmProfile, Date saleDate, String salesOrg,
			String distrChan, String methodPayment, String paymentTerm,
			String salesGroup, String orderType, Date creationDate,
			Set<CrmSaleOrderDetail> crmSaleOrderDetails) {
		this.crmPatient = crmPatient;
		this.crmUser = crmUser;
		this.crmProfile = crmProfile;
		this.saleDate = saleDate;
		this.salesOrg = salesOrg;
		this.distrChan = distrChan;
		this.methodPayment = methodPayment;
		this.paymentTerm = paymentTerm;
		this.salesGroup = salesGroup;
		this.orderType = orderType;
		this.creationDate = creationDate;
		this.crmSaleOrderDetails = crmSaleOrderDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_patient", nullable = false)
	public CrmPatient getCrmPatient() {
		return this.crmPatient;
	}

	public void setCrmPatient(CrmPatient crmPatient) {
		this.crmPatient = crmPatient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_user", nullable = false)
	public CrmUser getCrmUser() {
		return this.crmUser;
	}

	public void setCrmUser(CrmUser crmUser) {
		this.crmUser = crmUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_profile", nullable = false)
	public CrmProfile getCrmProfile() {
		return this.crmProfile;
	}

	public void setCrmProfile(CrmProfile crmProfile) {
		this.crmProfile = crmProfile;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "sale_date", nullable = false, length = 10)
	public Date getSaleDate() {
		return this.saleDate;
	}

	public void setSaleDate(Date saleDate) {
		this.saleDate = saleDate;
	}

	@Column(name = "sales_org", nullable = false, length = 45)
	public String getSalesOrg() {
		return this.salesOrg;
	}

	public void setSalesOrg(String salesOrg) {
		this.salesOrg = salesOrg;
	}

	@Column(name = "distr_chan", nullable = false, length = 45)
	public String getDistrChan() {
		return this.distrChan;
	}

	public void setDistrChan(String distrChan) {
		this.distrChan = distrChan;
	}

	@Column(name = "method_payment", nullable = false, length = 45)
	public String getMethodPayment() {
		return this.methodPayment;
	}

	public void setMethodPayment(String methodPayment) {
		this.methodPayment = methodPayment;
	}

	@Column(name = "payment_term", nullable = false, length = 45)
	public String getPaymentTerm() {
		return this.paymentTerm;
	}

	public void setPaymentTerm(String paymentTerm) {
		this.paymentTerm = paymentTerm;
	}

	@Column(name = "sales_group", nullable = false, length = 45)
	public String getSalesGroup() {
		return this.salesGroup;
	}

	public void setSalesGroup(String salesGroup) {
		this.salesGroup = salesGroup;
	}

	@Column(name = "order_type", nullable = false, length = 45)
	public String getOrderType() {
		return this.orderType;
	}

	public void setOrderType(String orderType) {
		this.orderType = orderType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "creation_date", nullable = false, length = 10)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmSaleOrder")
	public Set<CrmSaleOrderDetail> getCrmSaleOrderDetails() {
		return this.crmSaleOrderDetails;
	}

	public void setCrmSaleOrderDetails(
			Set<CrmSaleOrderDetail> crmSaleOrderDetails) {
		this.crmSaleOrderDetails = crmSaleOrderDetails;
	}

}
