package co.com.tactusoft.crm.model.entities;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CrmSpeciality generated by hbm2java
 */
@Entity
@Table(name = "crm_speciality", catalog = "crm_db", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class CrmSpeciality implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private String code;
	private String description;
	private int state;
	private Set<CrmDoctor> crmDoctors = new HashSet<CrmDoctor>(0);

	public CrmSpeciality() {
	}

	public CrmSpeciality(BigDecimal id, String description, int state) {
		this.id = id;
		this.description = description;
		this.state = state;
	}

	public CrmSpeciality(BigDecimal id, String code, String description,
			int state, Set<CrmDoctor> crmDoctors) {
		this.id = id;
		this.code = code;
		this.description = description;
		this.state = state;
		this.crmDoctors = crmDoctors;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "code", unique = true, length = 45)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmSpeciality")
	public Set<CrmDoctor> getCrmDoctors() {
		return this.crmDoctors;
	}

	public void setCrmDoctors(Set<CrmDoctor> crmDoctors) {
		this.crmDoctors = crmDoctors;
	}

}
