package co.com.tactusoft.crm.model.entities;

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CrmSaleOrderDetail generated by hbm2java
 */
@Entity
@Table(name = "crm_sale_order_detail", catalog = "crm_db")
public class CrmSaleOrderDetail implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private CrmSaleOrder crmSaleOrder;
	private String codMaterial;
	private String descMaterial;
	private BigDecimal price;
	private int amount;
	private Set<CrmCalcSchemeResult> crmCalcSchemeResults = new HashSet<CrmCalcSchemeResult>(
			0);

	public CrmSaleOrderDetail() {
	}

	public CrmSaleOrderDetail(CrmSaleOrder crmSaleOrder, String codMaterial,
			String descMaterial, BigDecimal price, int amount) {
		this.crmSaleOrder = crmSaleOrder;
		this.codMaterial = codMaterial;
		this.descMaterial = descMaterial;
		this.price = price;
		this.amount = amount;
	}

	public CrmSaleOrderDetail(CrmSaleOrder crmSaleOrder, String codMaterial,
			String descMaterial, BigDecimal price, int amount,
			Set<CrmCalcSchemeResult> crmCalcSchemeResults) {
		this.crmSaleOrder = crmSaleOrder;
		this.codMaterial = codMaterial;
		this.descMaterial = descMaterial;
		this.price = price;
		this.amount = amount;
		this.crmCalcSchemeResults = crmCalcSchemeResults;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_crm_sale_order", nullable = false)
	public CrmSaleOrder getCrmSaleOrder() {
		return this.crmSaleOrder;
	}

	public void setCrmSaleOrder(CrmSaleOrder crmSaleOrder) {
		this.crmSaleOrder = crmSaleOrder;
	}

	@Column(name = "cod_material", nullable = false, length = 18)
	public String getCodMaterial() {
		return this.codMaterial;
	}

	public void setCodMaterial(String codMaterial) {
		this.codMaterial = codMaterial;
	}

	@Column(name = "desc_material", nullable = false, length = 1000)
	public String getDescMaterial() {
		return this.descMaterial;
	}

	public void setDescMaterial(String descMaterial) {
		this.descMaterial = descMaterial;
	}

	@Column(name = "price", nullable = false, scale = 3)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "amount", nullable = false)
	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmSaleOrderDetail")
	public Set<CrmCalcSchemeResult> getCrmCalcSchemeResults() {
		return this.crmCalcSchemeResults;
	}

	public void setCrmCalcSchemeResults(
			Set<CrmCalcSchemeResult> crmCalcSchemeResults) {
		this.crmCalcSchemeResults = crmCalcSchemeResults;
	}

}
