package co.com.tactusoft.crm.model.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CrmTicket generated by hbm2java
 */
@Entity
@Table(name = "crm_ticket", catalog = "crm_db")
public class CrmTicket implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private Integer initialRange;
	private Integer finalRange;
	private int status;

	public CrmTicket() {
	}

	public CrmTicket(String name, int status) {
		this.name = name;
		this.status = status;
	}

	public CrmTicket(String name, Integer initialRange, Integer finalRange,
			int status) {
		this.name = name;
		this.initialRange = initialRange;
		this.finalRange = finalRange;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 1000)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "initial_range")
	public Integer getInitialRange() {
		return this.initialRange;
	}

	public void setInitialRange(Integer initialRange) {
		this.initialRange = initialRange;
	}

	@Column(name = "final_range")
	public Integer getFinalRange() {
		return this.finalRange;
	}

	public void setFinalRange(Integer finalRange) {
		this.finalRange = finalRange;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
