package co.com.tactusoft.crm.model.entities;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.LinkedList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CrmTerm generated by hbm2java
 */
@Entity
@Table(name = "crm_term", catalog = "crm_db", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class CrmTerm implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private String salesOrg;
	private String distrChan;
	private String division;
	private String society;
	private String orderReason;
	private String typeTerm;
	private String sign;
	private Byte status;
	private List<CrmTermMaterial> crmTermMaterials = new LinkedList<>();
	private List<CrmCalcSchemeDetail> crmCalcSchemeDetails = new LinkedList<>();

	public CrmTerm() {
	}

	public CrmTerm(String name, String salesOrg, String distrChan,
			String orderReason, String typeTerm, String sign) {
		this.name = name;
		this.salesOrg = salesOrg;
		this.distrChan = distrChan;
		this.orderReason = orderReason;
		this.typeTerm = typeTerm;
		this.sign = sign;
	}

	public CrmTerm(String name, String salesOrg, String distrChan,
			String division, String society, String orderReason,
			String typeTerm, String sign, Byte status,
			List<CrmTermMaterial> crmTermMaterials,
			List<CrmCalcSchemeDetail> crmCalcSchemeDetails) {
		this.name = name;
		this.salesOrg = salesOrg;
		this.distrChan = distrChan;
		this.division = division;
		this.society = society;
		this.orderReason = orderReason;
		this.typeTerm = typeTerm;
		this.sign = sign;
		this.status = status;
		this.crmTermMaterials = crmTermMaterials;
		this.crmCalcSchemeDetails = crmCalcSchemeDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "sales_org", nullable = false, length = 4)
	public String getSalesOrg() {
		return this.salesOrg;
	}

	public void setSalesOrg(String salesOrg) {
		this.salesOrg = salesOrg;
	}

	@Column(name = "distr_chan", nullable = false, length = 4)
	public String getDistrChan() {
		return this.distrChan;
	}

	public void setDistrChan(String distrChan) {
		this.distrChan = distrChan;
	}

	@Column(name = "division", length = 4)
	public String getDivision() {
		return this.division;
	}

	public void setDivision(String division) {
		this.division = division;
	}

	@Column(name = "society", length = 4)
	public String getSociety() {
		return this.society;
	}

	public void setSociety(String society) {
		this.society = society;
	}

	@Column(name = "order_reason", nullable = false, length = 45)
	public String getOrderReason() {
		return this.orderReason;
	}

	public void setOrderReason(String orderReason) {
		this.orderReason = orderReason;
	}

	@Column(name = "type_term", nullable = false, length = 1)
	public String getTypeTerm() {
		return this.typeTerm;
	}

	public void setTypeTerm(String typeTerm) {
		this.typeTerm = typeTerm;
	}

	@Column(name = "sign", nullable = false, length = 45)
	public String getSign() {
		return this.sign;
	}

	public void setSign(String sign) {
		this.sign = sign;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "crmTerm")
	public List<CrmTermMaterial> getCrmTermMaterials() {
		return this.crmTermMaterials;
	}

	public void setCrmTermMaterials(List<CrmTermMaterial> crmTermMaterials) {
		this.crmTermMaterials = crmTermMaterials;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmTerm")
	public List<CrmCalcSchemeDetail> getCrmCalcSchemeDetails() {
		return this.crmCalcSchemeDetails;
	}

	public void setCrmCalcSchemeDetails(
			List<CrmCalcSchemeDetail> crmCalcSchemeDetails) {
		this.crmCalcSchemeDetails = crmCalcSchemeDetails;
	}

	public String toString() {
		return name;
	}

}
