package co.com.tactusoft.crm.model.entities;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CrmUserProfile generated by hbm2java
 */
@Entity
@Table(name = "crm_user_profile", catalog = "crm_db", uniqueConstraints = @UniqueConstraint(columnNames = {
		"id_user", "id_profile" }))
public class CrmUserProfile implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private CrmUser crmUser;
	private CrmProfile crmProfile;

	public CrmUserProfile() {
	}

	public CrmUserProfile(BigDecimal id, CrmUser crmUser, CrmProfile crmProfile) {
		this.id = id;
		this.crmUser = crmUser;
		this.crmProfile = crmProfile;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_user", nullable = false)
	public CrmUser getCrmUser() {
		return this.crmUser;
	}

	public void setCrmUser(CrmUser crmUser) {
		this.crmUser = crmUser;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_profile", nullable = false)
	public CrmProfile getCrmProfile() {
		return this.crmProfile;
	}

	public void setCrmProfile(CrmProfile crmProfile) {
		this.crmProfile = crmProfile;
	}

}
