package co.com.tactusoft.crm.model.entities;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CrmUserRole generated by hbm2java
 */
@Entity
@Table(name = "crm_user_role", catalog = "crm_db")
public class CrmUserRole implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private CrmUser crmUser;
	private CrmRole crmRole;

	public CrmUserRole() {
	}

	public CrmUserRole(BigDecimal id, CrmUser crmUser, CrmRole crmRole) {
		this.id = id;
		this.crmUser = crmUser;
		this.crmRole = crmRole;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_user", nullable = false)
	public CrmUser getCrmUser() {
		return this.crmUser;
	}

	public void setCrmUser(CrmUser crmUser) {
		this.crmUser = crmUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_role", nullable = false)
	public CrmRole getCrmRole() {
		return this.crmRole;
	}

	public void setCrmRole(CrmRole crmRole) {
		this.crmRole = crmRole;
	}

}
