package co.com.tactusoft.crm.model.entities;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * IndRepurchase generated by hbm2java
 */
@Entity
public class IndRepurchase implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private String procedureName;
	private long patientsNumber;
	private BigDecimal purchaseTotal;
	private BigDecimal avgPurchase;

	public IndRepurchase() {
	}

	public IndRepurchase(BigDecimal id, String procedureName,
			long patientsNumber) {
		this.id = id;
		this.procedureName = procedureName;
		this.patientsNumber = patientsNumber;
	}

	public IndRepurchase(BigDecimal id, String procedureName,
			long patientsNumber, BigDecimal purchaseTotal,
			BigDecimal avgPurchase) {
		this.id = id;
		this.procedureName = procedureName;
		this.patientsNumber = patientsNumber;
		this.purchaseTotal = purchaseTotal;
		this.avgPurchase = avgPurchase;
	}

	@Id
	@Column(name = "id", nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "procedure_name", nullable = false)
	public String getProcedureName() {
		return this.procedureName;
	}

	public void setProcedureName(String procedureName) {
		this.procedureName = procedureName;
	}

	@Column(name = "patients_number", nullable = false)
	public long getPatientsNumber() {
		return this.patientsNumber;
	}

	public void setPatientsNumber(long patientsNumber) {
		this.patientsNumber = patientsNumber;
	}

	@Column(name = "purchase_total", precision = 32)
	public BigDecimal getPurchaseTotal() {
		return this.purchaseTotal;
	}

	public void setPurchaseTotal(BigDecimal purchaseTotal) {
		this.purchaseTotal = purchaseTotal;
	}

	@Column(name = "avg_purchase", precision = 14, scale = 6)
	public BigDecimal getAvgPurchase() {
		return this.avgPurchase;
	}

	public void setAvgPurchase(BigDecimal avgPurchase) {
		this.avgPurchase = avgPurchase;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IndRepurchase))
			return false;
		IndRepurchase castOther = (IndRepurchase) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getProcedureName() == castOther.getProcedureName()) || (this
						.getProcedureName() != null
						&& castOther.getProcedureName() != null && this
						.getProcedureName()
						.equals(castOther.getProcedureName())))
				&& (this.getPatientsNumber() == castOther.getPatientsNumber())
				&& ((this.getPurchaseTotal() == castOther.getPurchaseTotal()) || (this
						.getPurchaseTotal() != null
						&& castOther.getPurchaseTotal() != null && this
						.getPurchaseTotal()
						.equals(castOther.getPurchaseTotal())))
				&& ((this.getAvgPurchase() == castOther.getAvgPurchase()) || (this
						.getAvgPurchase() != null
						&& castOther.getAvgPurchase() != null && this
						.getAvgPurchase().equals(castOther.getAvgPurchase())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37
				* result
				+ (getProcedureName() == null ? 0 : this.getProcedureName()
						.hashCode());
		result = 37 * result + (int) this.getPatientsNumber();
		result = 37
				* result
				+ (getPurchaseTotal() == null ? 0 : this.getPurchaseTotal()
						.hashCode());
		result = 37
				* result
				+ (getAvgPurchase() == null ? 0 : this.getAvgPurchase()
						.hashCode());
		return result;
	}

}
