package co.com.tactusoft.crm.model.entities;

// Generated 17/08/2013 10:28:56 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedNativeQueries;
import javax.persistence.NamedNativeQuery;

/**
 * PrcReportCampaign generated by hbm2java
 */
@Entity
@NamedNativeQueries({ @NamedNativeQuery(name = "callPrcReportCampaign", query = "CALL prc_report_campaign(:start_date,:end_date,:branchs)", resultClass = PrcReportCampaign.class) })
public class PrcReportCampaign implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private BigDecimal branchId;
	private String branchName;
	private int campaignTypeId;
	private String campaignTypeName;
	private int totalAttendet;
	private int total;
	private BigDecimal percent;

	public PrcReportCampaign() {
	}

	public PrcReportCampaign(BigDecimal branchId, String branchName,
			int campaignTypeId, String campaignTypeName, int totalAttendet,
			int total, BigDecimal percent) {
		this.branchId = branchId;
		this.branchName = branchName;
		this.campaignTypeId = campaignTypeId;
		this.campaignTypeName = campaignTypeName;
		this.totalAttendet = totalAttendet;
		this.total = total;
		this.percent = percent;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "branch_id", nullable = false, scale = 0)
	public BigDecimal getBranchId() {
		return this.branchId;
	}

	public void setBranchId(BigDecimal branchId) {
		this.branchId = branchId;
	}

	@Column(name = "branch_name", nullable = false, length = 1000)
	public String getBranchName() {
		return this.branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	@Column(name = "campaign_type_id", nullable = false)
	public int getCampaignTypeId() {
		return this.campaignTypeId;
	}

	public void setCampaignTypeId(int campaignTypeId) {
		this.campaignTypeId = campaignTypeId;
	}

	@Column(name = "campaign_type_name", nullable = false, length = 45)
	public String getCampaignTypeName() {
		return this.campaignTypeName;
	}

	public void setCampaignTypeName(String campaignTypeName) {
		this.campaignTypeName = campaignTypeName;
	}

	@Column(name = "total_attendet", nullable = false)
	public int getTotalAttendet() {
		return this.totalAttendet;
	}

	public void setTotalAttendet(int totalAttendet) {
		this.totalAttendet = totalAttendet;
	}

	@Column(name = "total", nullable = false)
	public int getTotal() {
		return this.total;
	}

	public void setTotal(int total) {
		this.total = total;
	}

	@Column(name = "percent", nullable = false, precision = 10, scale = 4)
	public BigDecimal getPercent() {
		return this.percent;
	}

	public void setPercent(BigDecimal percent) {
		this.percent = percent;
	}

}
