package co.com.tactusoft.crm.model.entities;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VwRipsTransactionId generated by hbm2java
 */
@Embeddable
public class VwAppointmentBranchId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal branchId;
	private String status;

	public VwAppointmentBranchId() {
	}

	public VwAppointmentBranchId(BigDecimal branchId, String status) {
		this.branchId = branchId;
		this.status = status;
	}

	@Column(name = "branchId")
	public BigDecimal getBranchId() {
		return branchId;
	}

	public void setBranchId(BigDecimal branchId) {
		this.branchId = branchId;
	}

	@Column(name = "status")
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
