package co.com.tactusoft.crm.model.entities;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VwAppointmentMedicationId generated by hbm2java
 */
@Embeddable
public class VwAppointmentMedicationId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private long codMaterial;

	public VwAppointmentMedicationId() {
	}

	public VwAppointmentMedicationId(BigDecimal id, long codMaterial) {
		this.id = id;
		this.codMaterial = codMaterial;
	}

	@Column(name = "id", nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "cod_material", nullable = false)
	public long getCodMaterial() {
		return this.codMaterial;
	}

	public void setCodMaterial(long codMaterial) {
		this.codMaterial = codMaterial;
	}
}
