package co.com.tactusoft.crm.model.entities;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VwAppointmentAvgId generated by hbm2java
 */
@Embeddable
public class VwAppointmentAvgId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal branchId;
	private BigDecimal procedureId;

	public VwAppointmentAvgId() {
	}

	public VwAppointmentAvgId(BigDecimal branchId, BigDecimal procedureId) {
		this.branchId = branchId;
		this.procedureId = procedureId;
	}

	@Column(name = "branch_id", nullable = false, scale = 0)
	public BigDecimal getBranchId() {
		return this.branchId;
	}

	public void setBranchId(BigDecimal branchId) {
		this.branchId = branchId;
	}
	
	@Column(name = "procedure_id", nullable = false, scale = 0)
	public BigDecimal getProcedureId() {
		return this.procedureId;
	}

	public void setProcedureId(BigDecimal procedureId) {
		this.procedureId = procedureId;
	}
}
