package co.com.tactusoft.crm.model.entities;

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwAppointmentAvg generated by hbm2java
 */
@Entity
@Table(name = "vw_appointment_avg", catalog = "crm_db")
public class VwAppointmentAvg implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private VwAppointmentAvgId id;
	private String branchName;
	private String procedureName;
	private BigDecimal appointmentAvg;
	private BigDecimal appointmentCount;
	private BigDecimal appointmentSum;

	public VwAppointmentAvg() {
	}

	public VwAppointmentAvg(VwAppointmentAvgId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "branchId", column = @Column(name = "branch_id", nullable = false, scale = 0)),
			@AttributeOverride(name = "procedureId", column = @Column(name = "procedure_id", nullable = false, scale = 0)) })
	public VwAppointmentAvgId getId() {
		return this.id;
	}

	public void setId(VwAppointmentAvgId id) {
		this.id = id;
	}

	@Column(name = "branch_name", length = 1000)
	public String getBranchName() {
		return this.branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	@Column(name = "procedure_name", nullable = false)
	public String getProcedureName() {
		return this.procedureName;
	}

	public void setProcedureName(String procedureName) {
		this.procedureName = procedureName;
	}

	@Column(name = "appointment_avg", precision = 10, scale = 4)
	public BigDecimal getAppointmentAvg() {
		return this.appointmentAvg;
	}

	public void setAppointmentAvg(BigDecimal appointmentAvg) {
		this.appointmentAvg = appointmentAvg;
	}

	@Column(name = "appointment_count", precision = 10, scale = 4)
	public BigDecimal getAppointmentCount() {
		return appointmentCount;
	}

	public void setAppointmentCount(BigDecimal appointmentCount) {
		this.appointmentCount = appointmentCount;
	}

	@Column(name = "appointment_sum", precision = 10, scale = 4)
	public BigDecimal getAppointmentSum() {
		return appointmentSum;
	}

	public void setAppointmentSum(BigDecimal appointmentSum) {
		this.appointmentSum = appointmentSum;
	}

}
