package co.com.tactusoft.crm.model.entities;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwDoctorSchedule generated by hbm2java
 */
@Entity
@Table(name = "vw_doctor_schedule", catalog = "crm_db")
public class VwDoctorSchedule implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private VwDoctorScheduleId id;

	public VwDoctorSchedule() {
	}

	public VwDoctorSchedule(VwDoctorScheduleId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idDoctor", column = @Column(name = "id_doctor", nullable = false, scale = 0)),
			@AttributeOverride(name = "names", column = @Column(name = "names", nullable = false, length = 45)),
			@AttributeOverride(name = "idBranch", column = @Column(name = "id_branch", nullable = false, scale = 0)),
			@AttributeOverride(name = "day", column = @Column(name = "day", nullable = false)) })
	public VwDoctorScheduleId getId() {
		return this.id;
	}

	public void setId(VwDoctorScheduleId id) {
		this.id = id;
	}

}
