package co.com.tactusoft.crm.model.entities;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VwDoctorHourId generated by hbm2java
 */
@Embeddable
public class VwDoctorHourId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal idBranch;
	private BigDecimal idDoctor;
	private Date onlyDate;

	public VwDoctorHourId() {
	}

	public VwDoctorHourId(BigDecimal idBranch, BigDecimal idDoctor) {
		this.idBranch = idBranch;
		this.idDoctor = idDoctor;
	}

	public VwDoctorHourId(BigDecimal idBranch, BigDecimal idDoctor,
			Date onlyDate) {
		this.idBranch = idBranch;
		this.idDoctor = idDoctor;
		this.onlyDate = onlyDate;
	}

	@Column(name = "id_branch", nullable = false, scale = 0)
	public BigDecimal getIdBranch() {
		return this.idBranch;
	}

	public void setIdBranch(BigDecimal idBranch) {
		this.idBranch = idBranch;
	}

	@Column(name = "id_doctor", nullable = false, scale = 0)
	public BigDecimal getIdDoctor() {
		return this.idDoctor;
	}

	public void setIdDoctor(BigDecimal idDoctor) {
		this.idDoctor = idDoctor;
	}

	@Column(name = "only_date", length = 10)
	public Date getOnlyDate() {
		return this.onlyDate;
	}

	public void setOnlyDate(Date onlyDate) {
		this.onlyDate = onlyDate;
	}

}
