package co.com.tactusoft.crm.model.entities;

// Generated 27/08/2013 06:27:25 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VwMedicationSold generated by hbm2java
 */
@Entity
@Table(name = "vw_medication_sold", catalog = "crm_db")
public class VwMedicationSold implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private BigDecimal idAppointment;
	private BigDecimal idCie;
	private long codMaterial;
	private String descMaterial;
	private String sapMaterialType;
	private int unit;
	private int unitSold;
	private BigDecimal price;
	private String materialType;
	private String diagnosis;
	private String posology;
	private BigDecimal idPatient;
	private Date appointmentDate;
	private String doctorName;
	private String descCie;
	private int sold;

	public VwMedicationSold() {
	}

	public VwMedicationSold(BigDecimal id, BigDecimal idAppointment,
			long codMaterial, String descMaterial, int unit, int unitSold,
			String materialType, BigDecimal idPatient, String doctorName,
			int sold) {
		this.id = id;
		this.idAppointment = idAppointment;
		this.codMaterial = codMaterial;
		this.descMaterial = descMaterial;
		this.unit = unit;
		this.unitSold = unitSold;
		this.materialType = materialType;
		this.idPatient = idPatient;
		this.doctorName = doctorName;
		this.sold = sold;
	}

	public VwMedicationSold(BigDecimal id, BigDecimal idAppointment,
			BigDecimal idCie, long codMaterial, String descMaterial,
			String sapMaterialType, int unit, int unitSold, BigDecimal price,
			String materialType, String diagnosis, String posology,
			BigDecimal idPatient, Date appointmentDate, String doctorName,
			String descCie, int sold) {
		this.id = id;
		this.idAppointment = idAppointment;
		this.idCie = idCie;
		this.codMaterial = codMaterial;
		this.descMaterial = descMaterial;
		this.sapMaterialType = sapMaterialType;
		this.unit = unit;
		this.unitSold = unitSold;
		this.price = price;
		this.materialType = materialType;
		this.diagnosis = diagnosis;
		this.posology = posology;
		this.idPatient = idPatient;
		this.appointmentDate = appointmentDate;
		this.doctorName = doctorName;
		this.descCie = descCie;
		this.sold = sold;
	}

	@Id
	@Column(name = "id", nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "id_appointment", nullable = false, scale = 0)
	public BigDecimal getIdAppointment() {
		return this.idAppointment;
	}

	public void setIdAppointment(BigDecimal idAppointment) {
		this.idAppointment = idAppointment;
	}

	@Column(name = "id_cie", scale = 0)
	public BigDecimal getIdCie() {
		return this.idCie;
	}

	public void setIdCie(BigDecimal idCie) {
		this.idCie = idCie;
	}

	@Column(name = "cod_material", nullable = false)
	public long getCodMaterial() {
		return this.codMaterial;
	}

	public void setCodMaterial(long codMaterial) {
		this.codMaterial = codMaterial;
	}

	@Column(name = "desc_material", nullable = false, length = 1000)
	public String getDescMaterial() {
		return this.descMaterial;
	}

	public void setDescMaterial(String descMaterial) {
		this.descMaterial = descMaterial;
	}

	@Column(name = "sap_material_type", length = 4)
	public String getSapMaterialType() {
		return this.sapMaterialType;
	}

	public void setSapMaterialType(String sapMaterialType) {
		this.sapMaterialType = sapMaterialType;
	}

	@Column(name = "unit", nullable = false)
	public int getUnit() {
		return this.unit;
	}

	public void setUnit(int unit) {
		this.unit = unit;
	}

	@Column(name = "unit_sold", nullable = false)
	public int getUnitSold() {
		return unitSold;
	}

	public void setUnitSold(int unitSold) {
		this.unitSold = unitSold;
	}

	@Column(name = "price", precision = 15)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "material_type", nullable = false, length = 45)
	public String getMaterialType() {
		return this.materialType;
	}

	public void setMaterialType(String materialType) {
		this.materialType = materialType;
	}

	@Column(name = "diagnosis", length = 65535)
	public String getDiagnosis() {
		return this.diagnosis;
	}

	public void setDiagnosis(String diagnosis) {
		this.diagnosis = diagnosis;
	}

	@Column(name = "posology", length = 65535)
	public String getPosology() {
		return this.posology;
	}

	public void setPosology(String posology) {
		this.posology = posology;
	}

	@Column(name = "id_patient", nullable = false, scale = 0)
	public BigDecimal getIdPatient() {
		return this.idPatient;
	}

	public void setIdPatient(BigDecimal idPatient) {
		this.idPatient = idPatient;
	}

	@Column(name = "appointment_date", length = 10)
	public Date getAppointmentDate() {
		return this.appointmentDate;
	}

	public void setAppointmentDate(Date appointmentDate) {
		this.appointmentDate = appointmentDate;
	}

	@Column(name = "doctor_name", nullable = false, length = 45)
	public String getDoctorName() {
		return this.doctorName;
	}

	public void setDoctorName(String doctorName) {
		this.doctorName = doctorName;
	}

	@Column(name = "desc_cie", length = 1000)
	public String getDescCie() {
		return this.descCie;
	}

	public void setDescCie(String descCie) {
		this.descCie = descCie;
	}

	@Column(name = "sold", nullable = false)
	public int getSold() {
		return this.sold;
	}

	public void setSold(int sold) {
		this.sold = sold;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VwMedicationSold))
			return false;
		VwMedicationSold castOther = (VwMedicationSold) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getIdAppointment() == castOther.getIdAppointment()) || (this
						.getIdAppointment() != null
						&& castOther.getIdAppointment() != null && this
						.getIdAppointment()
						.equals(castOther.getIdAppointment())))
				&& ((this.getIdCie() == castOther.getIdCie()) || (this
						.getIdCie() != null && castOther.getIdCie() != null && this
						.getIdCie().equals(castOther.getIdCie())))
				&& (this.getCodMaterial() == castOther.getCodMaterial())
				&& ((this.getDescMaterial() == castOther.getDescMaterial()) || (this
						.getDescMaterial() != null
						&& castOther.getDescMaterial() != null && this
						.getDescMaterial().equals(castOther.getDescMaterial())))
				&& ((this.getSapMaterialType() == castOther
						.getSapMaterialType()) || (this.getSapMaterialType() != null
						&& castOther.getSapMaterialType() != null && this
						.getSapMaterialType().equals(
								castOther.getSapMaterialType())))
				&& (this.getUnit() == castOther.getUnit())
				&& ((this.getPrice() == castOther.getPrice()) || (this
						.getPrice() != null && castOther.getPrice() != null && this
						.getPrice().equals(castOther.getPrice())))
				&& ((this.getMaterialType() == castOther.getMaterialType()) || (this
						.getMaterialType() != null
						&& castOther.getMaterialType() != null && this
						.getMaterialType().equals(castOther.getMaterialType())))
				&& ((this.getDiagnosis() == castOther.getDiagnosis()) || (this
						.getDiagnosis() != null
						&& castOther.getDiagnosis() != null && this
						.getDiagnosis().equals(castOther.getDiagnosis())))
				&& ((this.getPosology() == castOther.getPosology()) || (this
						.getPosology() != null
						&& castOther.getPosology() != null && this
						.getPosology().equals(castOther.getPosology())))
				&& ((this.getIdPatient() == castOther.getIdPatient()) || (this
						.getIdPatient() != null
						&& castOther.getIdPatient() != null && this
						.getIdPatient().equals(castOther.getIdPatient())))
				&& ((this.getAppointmentDate() == castOther
						.getAppointmentDate()) || (this.getAppointmentDate() != null
						&& castOther.getAppointmentDate() != null && this
						.getAppointmentDate().equals(
								castOther.getAppointmentDate())))
				&& ((this.getDoctorName() == castOther.getDoctorName()) || (this
						.getDoctorName() != null
						&& castOther.getDoctorName() != null && this
						.getDoctorName().equals(castOther.getDoctorName())))
				&& ((this.getDescCie() == castOther.getDescCie()) || (this
						.getDescCie() != null && castOther.getDescCie() != null && this
						.getDescCie().equals(castOther.getDescCie())))
				&& (this.getSold() == castOther.getSold());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37
				* result
				+ (getIdAppointment() == null ? 0 : this.getIdAppointment()
						.hashCode());
		result = 37 * result
				+ (getIdCie() == null ? 0 : this.getIdCie().hashCode());
		result = 37 * result + (int) this.getCodMaterial();
		result = 37
				* result
				+ (getDescMaterial() == null ? 0 : this.getDescMaterial()
						.hashCode());
		result = 37
				* result
				+ (getSapMaterialType() == null ? 0 : this.getSapMaterialType()
						.hashCode());
		result = 37 * result + this.getUnit();
		result = 37 * result
				+ (getPrice() == null ? 0 : this.getPrice().hashCode());
		result = 37
				* result
				+ (getMaterialType() == null ? 0 : this.getMaterialType()
						.hashCode());
		result = 37 * result
				+ (getDiagnosis() == null ? 0 : this.getDiagnosis().hashCode());
		result = 37 * result
				+ (getPosology() == null ? 0 : this.getPosology().hashCode());
		result = 37 * result
				+ (getIdPatient() == null ? 0 : this.getIdPatient().hashCode());
		result = 37
				* result
				+ (getAppointmentDate() == null ? 0 : this.getAppointmentDate()
						.hashCode());
		result = 37
				* result
				+ (getDoctorName() == null ? 0 : this.getDoctorName()
						.hashCode());
		result = 37 * result
				+ (getDescCie() == null ? 0 : this.getDescCie().hashCode());
		result = 37 * result + this.getSold();
		return result;
	}

}
