package co.com.tactusoft.crm.model.entities;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VwMedicationId generated by hbm2java
 */
@Entity
@Table(name = "vw_medication", catalog = "crm_db")
public class VwMedication implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private BigDecimal idAppointment;
	private String formulaDocType;
	private long codMaterial;
	private String descMaterial;
	private String posology;
	private int sold;
	private int unit;
	private int saleUnit;
	private BigDecimal price;
	private BigDecimal salePrice;

	public VwMedication() {
	}

	public VwMedication(BigDecimal id, BigDecimal idAppointment,
			long codMaterial, String descMaterial, int sold, int unit,
			int saleUnit, BigDecimal price, BigDecimal salePrice) {
		this.id = id;
		this.idAppointment = idAppointment;
		this.codMaterial = codMaterial;
		this.descMaterial = descMaterial;
		this.sold = sold;
		this.unit = unit;
		this.saleUnit = saleUnit;
		this.price = price;
		this.salePrice = salePrice;
	}

	public VwMedication(BigDecimal id, BigDecimal idAppointment,
			String formulaDocType, long codMaterial, String descMaterial,
			String posology, int sold, int unit, int saleUnit,
			BigDecimal price, BigDecimal salePrice) {
		this.id = id;
		this.idAppointment = idAppointment;
		this.formulaDocType = formulaDocType;
		this.codMaterial = codMaterial;
		this.descMaterial = descMaterial;
		this.posology = posology;
		this.sold = sold;
		this.unit = unit;
		this.saleUnit = saleUnit;
		this.price = price;
		this.salePrice = salePrice;
	}

	@Id
	@Column(name = "id", nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "id_appointment", nullable = false, scale = 0)
	public BigDecimal getIdAppointment() {
		return this.idAppointment;
	}

	public void setIdAppointment(BigDecimal idAppointment) {
		this.idAppointment = idAppointment;
	}

	@Column(name = "formula_doc_type", length = 65535)
	public String getFormulaDocType() {
		return this.formulaDocType;
	}

	public void setFormulaDocType(String formulaDocType) {
		this.formulaDocType = formulaDocType;
	}

	@Column(name = "cod_material", nullable = false)
	public long getCodMaterial() {
		return this.codMaterial;
	}

	public void setCodMaterial(long codMaterial) {
		this.codMaterial = codMaterial;
	}

	@Column(name = "desc_material", nullable = false, length = 1000)
	public String getDescMaterial() {
		return this.descMaterial;
	}

	public void setDescMaterial(String descMaterial) {
		this.descMaterial = descMaterial;
	}

	@Column(name = "posology", length = 65535)
	public String getPosology() {
		return this.posology;
	}

	public void setPosology(String posology) {
		this.posology = posology;
	}

	@Column(name = "sold", nullable = false)
	public int getSold() {
		return this.sold;
	}

	public void setSold(int sold) {
		this.sold = sold;
	}

	@Column(name = "unit", nullable = false)
	public int getUnit() {
		return this.unit;
	}

	public void setUnit(int unit) {
		this.unit = unit;
	}

	@Column(name = "sale_unit", nullable = false)
	public int getSaleUnit() {
		return this.saleUnit;
	}

	public void setSaleUnit(int saleUnit) {
		this.saleUnit = saleUnit;
	}

	@Column(name = "price", nullable = false, precision = 15)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "sale_price", nullable = false, precision = 10)
	public BigDecimal getSalePrice() {
		return this.salePrice;
	}

	public void setSalePrice(BigDecimal salePrice) {
		this.salePrice = salePrice;
	}

}
