package co.com.tactusoft.crm.model.entities;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VwPatientAccountMarketing generated by hbm2java
 */
@Entity
@Table(name = "vw_patient_account_marketing", catalog = "crm_db")
public class VwPatientAccountMarketing implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private String pacientDoc;
	private String patientNames;
	private String patientSurnames;
	private Date createDate;
	private String username;
	private String userNames;
	private String userSurnames;
	private BigDecimal branchId;
	private String branchCode;
	private String brancheName;
	private String obs;
	private BigDecimal idGroup;
	private String groupName;
	private Integer idMarketingActivity;
	private String marketingName;

	public VwPatientAccountMarketing() {
	}

	public VwPatientAccountMarketing(BigDecimal id, String patientNames,
			String patientSurnames, Date createDate, String username,
			String userNames, String userSurnames, BigDecimal branchId) {
		this.id = id;
		this.patientNames = patientNames;
		this.patientSurnames = patientSurnames;
		this.createDate = createDate;
		this.username = username;
		this.userNames = userNames;
		this.userSurnames = userSurnames;
		this.branchId = branchId;
	}

	public VwPatientAccountMarketing(BigDecimal id, String pacientDoc,
			String patientNames, String patientSurnames, Date createDate,
			String username, String userNames, String userSurnames,
			BigDecimal branchId, String branchCode, String brancheName,
			String obs, BigDecimal idGroup, String groupName,
			Integer idMarketingActivity, String marketingName) {
		this.id = id;
		this.pacientDoc = pacientDoc;
		this.patientNames = patientNames;
		this.patientSurnames = patientSurnames;
		this.createDate = createDate;
		this.username = username;
		this.userNames = userNames;
		this.userSurnames = userSurnames;
		this.branchId = branchId;
		this.branchCode = branchCode;
		this.brancheName = brancheName;
		this.obs = obs;
		this.idGroup = idGroup;
		this.groupName = groupName;
		this.idMarketingActivity = idMarketingActivity;
		this.marketingName = marketingName;
	}

	@Id
	@Column(name = "id", nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "pacient_doc", length = 45)
	public String getPacientDoc() {
		return this.pacientDoc;
	}

	public void setPacientDoc(String pacientDoc) {
		this.pacientDoc = pacientDoc;
	}

	@Column(name = "patient_names", nullable = false, length = 45)
	public String getPatientNames() {
		return this.patientNames;
	}

	public void setPatientNames(String patientNames) {
		this.patientNames = patientNames;
	}

	@Column(name = "patient_surnames", nullable = false, length = 45)
	public String getPatientSurnames() {
		return this.patientSurnames;
	}

	public void setPatientSurnames(String patientSurnames) {
		this.patientSurnames = patientSurnames;
	}

	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "username", nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "user_names", nullable = false)
	public String getUserNames() {
		return this.userNames;
	}

	public void setUserNames(String userNames) {
		this.userNames = userNames;
	}

	@Column(name = "user_surnames", nullable = false)
	public String getUserSurnames() {
		return this.userSurnames;
	}

	public void setUserSurnames(String userSurnames) {
		this.userSurnames = userSurnames;
	}

	@Column(name = "branch_id", nullable = false, scale = 0)
	public BigDecimal getBranchId() {
		return this.branchId;
	}

	public void setBranchId(BigDecimal branchId) {
		this.branchId = branchId;
	}

	@Column(name = "branch_code", length = 45)
	public String getBranchCode() {
		return this.branchCode;
	}

	public void setBranchCode(String branchCode) {
		this.branchCode = branchCode;
	}

	@Column(name = "branche_name", length = 1000)
	public String getBrancheName() {
		return this.brancheName;
	}

	public void setBrancheName(String brancheName) {
		this.brancheName = brancheName;
	}

	@Column(name = "obs", length = 65535)
	public String getObs() {
		return this.obs;
	}

	public void setObs(String obs) {
		this.obs = obs;
	}

	@Column(name = "id_group", scale = 0)
	public BigDecimal getIdGroup() {
		return this.idGroup;
	}

	public void setIdGroup(BigDecimal idGroup) {
		this.idGroup = idGroup;
	}

	@Column(name = "group_name", length = 45)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@Column(name = "id_marketing_activity")
	public Integer getIdMarketingActivity() {
		return this.idMarketingActivity;
	}

	public void setIdMarketingActivity(Integer idMarketingActivity) {
		this.idMarketingActivity = idMarketingActivity;
	}

	@Column(name = "marketing_name")
	public String getMarketingName() {
		return this.marketingName;
	}

	public void setMarketingName(String marketingName) {
		this.marketingName = marketingName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VwPatientAccountMarketing))
			return false;
		VwPatientAccountMarketing castOther = (VwPatientAccountMarketing) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getPacientDoc() == castOther.getPacientDoc()) || (this
						.getPacientDoc() != null
						&& castOther.getPacientDoc() != null && this
						.getPacientDoc().equals(castOther.getPacientDoc())))
				&& ((this.getPatientNames() == castOther.getPatientNames()) || (this
						.getPatientNames() != null
						&& castOther.getPatientNames() != null && this
						.getPatientNames().equals(castOther.getPatientNames())))
				&& ((this.getPatientSurnames() == castOther
						.getPatientSurnames()) || (this.getPatientSurnames() != null
						&& castOther.getPatientSurnames() != null && this
						.getPatientSurnames().equals(
								castOther.getPatientSurnames())))
				&& ((this.getCreateDate() == castOther.getCreateDate()) || (this
						.getCreateDate() != null
						&& castOther.getCreateDate() != null && this
						.getCreateDate().equals(castOther.getCreateDate())))
				&& ((this.getUsername() == castOther.getUsername()) || (this
						.getUsername() != null
						&& castOther.getUsername() != null && this
						.getUsername().equals(castOther.getUsername())))
				&& ((this.getUserNames() == castOther.getUserNames()) || (this
						.getUserNames() != null
						&& castOther.getUserNames() != null && this
						.getUserNames().equals(castOther.getUserNames())))
				&& ((this.getUserSurnames() == castOther.getUserSurnames()) || (this
						.getUserSurnames() != null
						&& castOther.getUserSurnames() != null && this
						.getUserSurnames().equals(castOther.getUserSurnames())))
				&& ((this.getBranchId() == castOther.getBranchId()) || (this
						.getBranchId() != null
						&& castOther.getBranchId() != null && this
						.getBranchId().equals(castOther.getBranchId())))
				&& ((this.getBranchCode() == castOther.getBranchCode()) || (this
						.getBranchCode() != null
						&& castOther.getBranchCode() != null && this
						.getBranchCode().equals(castOther.getBranchCode())))
				&& ((this.getBrancheName() == castOther.getBrancheName()) || (this
						.getBrancheName() != null
						&& castOther.getBrancheName() != null && this
						.getBrancheName().equals(castOther.getBrancheName())))
				&& ((this.getObs() == castOther.getObs()) || (this.getObs() != null
						&& castOther.getObs() != null && this.getObs().equals(
						castOther.getObs())))
				&& ((this.getIdGroup() == castOther.getIdGroup()) || (this
						.getIdGroup() != null && castOther.getIdGroup() != null && this
						.getIdGroup().equals(castOther.getIdGroup())))
				&& ((this.getGroupName() == castOther.getGroupName()) || (this
						.getGroupName() != null
						&& castOther.getGroupName() != null && this
						.getGroupName().equals(castOther.getGroupName())))
				&& ((this.getIdMarketingActivity() == castOther
						.getIdMarketingActivity()) || (this
						.getIdMarketingActivity() != null
						&& castOther.getIdMarketingActivity() != null && this
						.getIdMarketingActivity().equals(
								castOther.getIdMarketingActivity())))
				&& ((this.getMarketingName() == castOther.getMarketingName()) || (this
						.getMarketingName() != null
						&& castOther.getMarketingName() != null && this
						.getMarketingName()
						.equals(castOther.getMarketingName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37
				* result
				+ (getPacientDoc() == null ? 0 : this.getPacientDoc()
						.hashCode());
		result = 37
				* result
				+ (getPatientNames() == null ? 0 : this.getPatientNames()
						.hashCode());
		result = 37
				* result
				+ (getPatientSurnames() == null ? 0 : this.getPatientSurnames()
						.hashCode());
		result = 37
				* result
				+ (getCreateDate() == null ? 0 : this.getCreateDate()
						.hashCode());
		result = 37 * result
				+ (getUsername() == null ? 0 : this.getUsername().hashCode());
		result = 37 * result
				+ (getUserNames() == null ? 0 : this.getUserNames().hashCode());
		result = 37
				* result
				+ (getUserSurnames() == null ? 0 : this.getUserSurnames()
						.hashCode());
		result = 37 * result
				+ (getBranchId() == null ? 0 : this.getBranchId().hashCode());
		result = 37
				* result
				+ (getBranchCode() == null ? 0 : this.getBranchCode()
						.hashCode());
		result = 37
				* result
				+ (getBrancheName() == null ? 0 : this.getBrancheName()
						.hashCode());
		result = 37 * result
				+ (getObs() == null ? 0 : this.getObs().hashCode());
		result = 37 * result
				+ (getIdGroup() == null ? 0 : this.getIdGroup().hashCode());
		result = 37 * result
				+ (getGroupName() == null ? 0 : this.getGroupName().hashCode());
		result = 37
				* result
				+ (getIdMarketingActivity() == null ? 0 : this
						.getIdMarketingActivity().hashCode());
		result = 37
				* result
				+ (getMarketingName() == null ? 0 : this.getMarketingName()
						.hashCode());
		return result;
	}

}
