package co.com.tactusoft.crm.model.entities;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VwProcedure generated by hbm2java
 */
@Entity
@Table(name = "vw_procedure", catalog = "crm_db")
public class VwProcedure implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private String nameProcedure;
	private String nameProcedureDetail;
	private BigDecimal idBranch;

	public VwProcedure() {
	}

	public VwProcedure(BigDecimal id, String nameProcedure,
			String nameProcedureDetail, BigDecimal idBranch) {
		this.id = id;
		this.nameProcedure = nameProcedure;
		this.nameProcedureDetail = nameProcedureDetail;
		this.idBranch = idBranch;
	}

	@Id
	@Column(name = "id", nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "name_procedure", nullable = false)
	public String getNameProcedure() {
		return this.nameProcedure;
	}

	public void setNameProcedure(String nameProcedure) {
		this.nameProcedure = nameProcedure;
	}

	@Column(name = "name_procedure_detail", nullable = false)
	public String getNameProcedureDetail() {
		return this.nameProcedureDetail;
	}

	public void setNameProcedureDetail(String nameProcedureDetail) {
		this.nameProcedureDetail = nameProcedureDetail;
	}

	@Column(name = "id_branch", nullable = false, scale = 0)
	public BigDecimal getIdBranch() {
		return this.idBranch;
	}

	public void setIdBranch(BigDecimal idBranch) {
		this.idBranch = idBranch;
	}

}
