package co.com.tactusoft.crm.model.entities;

// Generated 24-abr-2013 14:52:22 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VwRipsPatient generated by hbm2java
 */
@Entity
@Table(name = "vw_rips_patient", catalog = "crm_db")
public class VwRipsPatient implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal idPatient;
	private BigDecimal idBranch;
	private Date appointmentDate;
	private String branch;
	private String docType;
	private String doc;
	private int membership;
	private String surnames;
	private String surnames2;
	private String firstnames;
	private String firstnames2;
	private Double age;
	private int sizeUnit;
	private String gender;
	private String region;
	private String city;
	private String typeHousing;
	private BigDecimal idEps;
	private String typeHistory;

	public VwRipsPatient() {
	}

	public VwRipsPatient(BigDecimal idPatient, BigDecimal idBranch,
			int membership, String surnames, String surnames2,
			String firstnames, String firstnames2, Double age, int sizeUnit,
			String gender, String typeHousing, String typeHistory) {
		this.idPatient = idPatient;
		this.idBranch = idBranch;
		this.membership = membership;
		this.surnames = surnames;
		this.surnames2 = surnames2;
		this.firstnames = firstnames;
		this.firstnames2 = firstnames2;
		this.age = age;
		this.sizeUnit = sizeUnit;
		this.gender = gender;
		this.typeHousing = typeHousing;
		this.typeHistory = typeHistory;
	}

	public VwRipsPatient(BigDecimal idPatient, BigDecimal idBranch,
			Date appointmentDate, String branch, String docType, String doc,
			int membership, String surnames, String surnames2,
			String firstnames, String firstnames2, Double age, int sizeUnit,
			String gender, String region, String city, BigDecimal idEps,
			String typeHousing) {
		this.idPatient = idPatient;
		this.idBranch = idBranch;
		this.appointmentDate = appointmentDate;
		this.branch = branch;
		this.docType = docType;
		this.doc = doc;
		this.membership = membership;
		this.surnames = surnames;
		this.surnames2 = surnames2;
		this.firstnames = firstnames;
		this.firstnames2 = firstnames2;
		this.age = age;
		this.sizeUnit = sizeUnit;
		this.gender = gender;
		this.region = region;
		this.city = city;
		this.idEps = idEps;
		this.typeHousing = typeHousing;
	}

	@Id
	@Column(name = "id_patient", nullable = false, scale = 0)
	public BigDecimal getIdPatient() {
		return this.idPatient;
	}

	public void setIdPatient(BigDecimal idPatient) {
		this.idPatient = idPatient;
	}

	@Column(name = "id_branch", nullable = false, scale = 0)
	public BigDecimal getIdBranch() {
		return this.idBranch;
	}

	public void setIdBranch(BigDecimal idBranch) {
		this.idBranch = idBranch;
	}

	@Column(name = "appointment_date", length = 10)
	public Date getAppointmentDate() {
		return this.appointmentDate;
	}

	public void setAppointmentDate(Date appointmentDate) {
		this.appointmentDate = appointmentDate;
	}

	@Column(name = "branch", length = 45)
	public String getBranch() {
		return this.branch;
	}

	public void setBranch(String branch) {
		this.branch = branch;
	}

	@Column(name = "doc_type", length = 2)
	public String getDocType() {
		return this.docType;
	}

	public void setDocType(String docType) {
		this.docType = docType;
	}

	@Column(name = "doc", length = 45)
	public String getDoc() {
		return this.doc;
	}

	public void setDoc(String doc) {
		this.doc = doc;
	}

	@Column(name = "membership", nullable = false)
	public int getMembership() {
		return this.membership;
	}

	public void setMembership(int membership) {
		this.membership = membership;
	}

	@Column(name = "surnames", nullable = false, length = 45)
	public String getSurnames() {
		return this.surnames;
	}

	public void setSurnames(String surnames) {
		this.surnames = surnames;
	}

	@Column(name = "surnames_2", nullable = false, length = 0)
	public String getSurnames2() {
		return this.surnames2;
	}

	public void setSurnames2(String surnames2) {
		this.surnames2 = surnames2;
	}

	@Column(name = "firstnames", nullable = false, length = 45)
	public String getFirstnames() {
		return this.firstnames;
	}

	public void setFirstnames(String firstnames) {
		this.firstnames = firstnames;
	}

	@Column(name = "firstnames_2", nullable = false, length = 0)
	public String getFirstnames2() {
		return this.firstnames2;
	}

	public void setFirstnames2(String firstnames2) {
		this.firstnames2 = firstnames2;
	}

	@Column(name = "age", nullable = false, precision = 17, scale = 0)
	public Double getAge() {
		return this.age;
	}

	public void setAge(Double age) {
		this.age = age;
	}

	@Column(name = "size_unit", nullable = false)
	public int getSizeUnit() {
		return this.sizeUnit;
	}

	public void setSizeUnit(int sizeUnit) {
		this.sizeUnit = sizeUnit;
	}

	@Column(name = "gender", nullable = false, length = 1)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "region", length = 2)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "city", length = 3)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "type_housing", nullable = false, length = 45)
	public String getTypeHousing() {
		return this.typeHousing;
	}

	public void setTypeHousing(String typeHousing) {
		this.typeHousing = typeHousing;
	}

	@Column(name = "id_eps", nullable = false, scale = 0)
	public BigDecimal getIdEps() {
		return idEps;
	}

	public void setIdEps(BigDecimal idEps) {
		this.idEps = idEps;
	}

	@Column(name = "type_history", nullable = false, length = 45)
	public String getTypeHistory() {
		return typeHistory;
	}

	public void setTypeHistory(String typeHistory) {
		this.typeHistory = typeHistory;
	}
}
