package co.com.tactusoft.crm.model.entities;

// Generated 24-abr-2013 14:52:22 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VwRipsTransactionId generated by hbm2java
 */
@Embeddable
public class VwRipsTransactionId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal idBranch;
	private Date appointmentDate;
	private String clinic;
	private String docType;
	private String doc;
	private String idBill;
	private Date dateBill;
	private String startDate;
	private String endDate;
	private String epsCode;
	private String epsName;
	private String contract;
	private String benefitPlan;
	private String policy;
	private int copayment;
	private int commission;
	private int discount;
	private BigDecimal amount;
	private String typeHistory;

	public VwRipsTransactionId() {
	}

	public VwRipsTransactionId(BigDecimal idBranch, String idBill,
			String startDate, String endDate, String epsCode, String epsName,
			String contract, String benefitPlan, String policy, int copayment,
			int commission, int discount) {
		this.idBranch = idBranch;
		this.idBill = idBill;
		this.startDate = startDate;
		this.endDate = endDate;
		this.epsCode = epsCode;
		this.epsName = epsName;
		this.contract = contract;
		this.benefitPlan = benefitPlan;
		this.policy = policy;
		this.copayment = copayment;
		this.commission = commission;
		this.discount = discount;
	}

	public VwRipsTransactionId(BigDecimal idBranch, Date appointmentDate,
			String clinic, String docType, String doc, String idBill,
			Date dateBill, String startDate, String endDate, String epsCode,
			String epsName, String contract, String benefitPlan, String policy,
			int copayment, int commission, int discount, BigDecimal amount,
			String typeHistory) {
		this.idBranch = idBranch;
		this.appointmentDate = appointmentDate;
		this.clinic = clinic;
		this.docType = docType;
		this.doc = doc;
		this.idBill = idBill;
		this.dateBill = dateBill;
		this.startDate = startDate;
		this.endDate = endDate;
		this.epsCode = epsCode;
		this.epsName = epsName;
		this.contract = contract;
		this.benefitPlan = benefitPlan;
		this.policy = policy;
		this.copayment = copayment;
		this.commission = commission;
		this.discount = discount;
		this.amount = amount;
		this.typeHistory = typeHistory;
	}

	@Column(name = "id_branch", nullable = false, scale = 0)
	public BigDecimal getIdBranch() {
		return this.idBranch;
	}

	public void setIdBranch(BigDecimal idBranch) {
		this.idBranch = idBranch;
	}

	@Column(name = "appointment_date", length = 10)
	public Date getAppointmentDate() {
		return this.appointmentDate;
	}

	public void setAppointmentDate(Date appointmentDate) {
		this.appointmentDate = appointmentDate;
	}

	@Column(name = "clinic", length = 45)
	public String getClinic() {
		return this.clinic;
	}

	public void setClinic(String clinic) {
		this.clinic = clinic;
	}

	@Column(name = "doc_type", length = 2)
	public String getDocType() {
		return this.docType;
	}

	public void setDocType(String docType) {
		this.docType = docType;
	}

	@Column(name = "doc", length = 30)
	public String getDoc() {
		return this.doc;
	}

	public void setDoc(String doc) {
		this.doc = doc;
	}

	@Column(name = "id_bill", nullable = false, length = 30)
	public String getIdBill() {
		return this.idBill;
	}

	public void setIdBill(String idBill) {
		this.idBill = idBill;
	}

	@Column(name = "date_bill", length = 19)
	public Date getDateBill() {
		return this.dateBill;
	}

	public void setDateBill(Date dateBill) {
		this.dateBill = dateBill;
	}

	@Column(name = "start_date", nullable = false, length = 0)
	public String getStartDate() {
		return this.startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	@Column(name = "end_date", nullable = false, length = 0)
	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	@Column(name = "eps_code", nullable = false, length = 0)
	public String getEpsCode() {
		return this.epsCode;
	}

	public void setEpsCode(String epsCode) {
		this.epsCode = epsCode;
	}

	@Column(name = "eps_name", nullable = false, length = 0)
	public String getEpsName() {
		return this.epsName;
	}

	public void setEpsName(String epsName) {
		this.epsName = epsName;
	}

	@Column(name = "contract", nullable = false, length = 0)
	public String getContract() {
		return this.contract;
	}

	public void setContract(String contract) {
		this.contract = contract;
	}

	@Column(name = "benefit_plan", nullable = false, length = 0)
	public String getBenefitPlan() {
		return this.benefitPlan;
	}

	public void setBenefitPlan(String benefitPlan) {
		this.benefitPlan = benefitPlan;
	}

	@Column(name = "policy", nullable = false, length = 0)
	public String getPolicy() {
		return this.policy;
	}

	public void setPolicy(String policy) {
		this.policy = policy;
	}

	@Column(name = "copayment", nullable = false)
	public int getCopayment() {
		return this.copayment;
	}

	public void setCopayment(int copayment) {
		this.copayment = copayment;
	}

	@Column(name = "commission", nullable = false)
	public int getCommission() {
		return this.commission;
	}

	public void setCommission(int commission) {
		this.commission = commission;
	}

	@Column(name = "discount", nullable = false)
	public int getDiscount() {
		return this.discount;
	}

	public void setDiscount(int discount) {
		this.discount = discount;
	}

	@Column(name = "amount", precision = 10)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "type_history")
	public String getTypeHistory() {
		return typeHistory;
	}

	public void setTypeHistory(String typeHistory) {
		this.typeHistory = typeHistory;
	}

}
