package co.com.tactusoft.crm.model.entities;

// Generated 24-abr-2013 14:52:22 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VwRipsMedicationId generated by hbm2java
 */
@Embeddable
public class VwRipsMedicationId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal idBranch;
	private Date appointmentDate;
	private String idBill;
	private String clinic;
	private String docType;
	private String doc;
	private String autorization;
	private String medicationCode;
	private String medicationType;
	private String medicationName;
	private String medicationForm;
	private String medicationConcentration;
	private String medicationSize;
	private Integer unit;
	private BigDecimal amount;
	private BigDecimal total;

	public VwRipsMedicationId() {
	}

	public VwRipsMedicationId(BigDecimal idBranch, String idBill,
			String autorization, String medicationType, String medicationForm,
			String medicationConcentration, String medicationSize) {
		this.idBranch = idBranch;
		this.idBill = idBill;
		this.autorization = autorization;
		this.medicationType = medicationType;
		this.medicationForm = medicationForm;
		this.medicationConcentration = medicationConcentration;
		this.medicationSize = medicationSize;
	}

	public VwRipsMedicationId(BigDecimal idBranch, Date appointmentDate,
			String idBill, String clinic, String docType, String doc,
			String autorization, String medicationCode, String medicationType,
			String medicationName, String medicationForm,
			String medicationConcentration, String medicationSize,
			Integer unit, BigDecimal amount, BigDecimal total) {
		this.idBranch = idBranch;
		this.appointmentDate = appointmentDate;
		this.idBill = idBill;
		this.clinic = clinic;
		this.docType = docType;
		this.doc = doc;
		this.autorization = autorization;
		this.medicationCode = medicationCode;
		this.medicationType = medicationType;
		this.medicationName = medicationName;
		this.medicationForm = medicationForm;
		this.medicationConcentration = medicationConcentration;
		this.medicationSize = medicationSize;
		this.unit = unit;
		this.amount = amount;
		this.total = total;
	}

	@Column(name = "id_branch", nullable = false, scale = 0)
	public BigDecimal getIdBranch() {
		return this.idBranch;
	}

	public void setIdBranch(BigDecimal idBranch) {
		this.idBranch = idBranch;
	}

	@Column(name = "appointment_date", length = 10)
	public Date getAppointmentDate() {
		return this.appointmentDate;
	}

	public void setAppointmentDate(Date appointmentDate) {
		this.appointmentDate = appointmentDate;
	}

	@Column(name = "id_bill", nullable = false, length = 30)
	public String getIdBill() {
		return this.idBill;
	}

	public void setIdBill(String idBill) {
		this.idBill = idBill;
	}

	@Column(name = "clinic", length = 45)
	public String getClinic() {
		return this.clinic;
	}

	public void setClinic(String clinic) {
		this.clinic = clinic;
	}

	@Column(name = "doc_type", length = 2)
	public String getDocType() {
		return this.docType;
	}

	public void setDocType(String docType) {
		this.docType = docType;
	}

	@Column(name = "doc", length = 30)
	public String getDoc() {
		return this.doc;
	}

	public void setDoc(String doc) {
		this.doc = doc;
	}

	@Column(name = "autorization", nullable = false, length = 0)
	public String getAutorization() {
		return this.autorization;
	}

	public void setAutorization(String autorization) {
		this.autorization = autorization;
	}

	@Column(name = "medication_code", length = 18)
	public String getMedicationCode() {
		return this.medicationCode;
	}

	public void setMedicationCode(String medicationCode) {
		this.medicationCode = medicationCode;
	}

	@Column(name = "medication_type", nullable = false, length = 0)
	public String getMedicationType() {
		return this.medicationType;
	}

	public void setMedicationType(String medicationType) {
		this.medicationType = medicationType;
	}

	@Column(name = "medication_name")
	public String getMedicationName() {
		return this.medicationName;
	}

	public void setMedicationName(String medicationName) {
		this.medicationName = medicationName;
	}

	@Column(name = "medication_form", nullable = false, length = 0)
	public String getMedicationForm() {
		return this.medicationForm;
	}

	public void setMedicationForm(String medicationForm) {
		this.medicationForm = medicationForm;
	}

	@Column(name = "medication_concentration", nullable = false, length = 0)
	public String getMedicationConcentration() {
		return this.medicationConcentration;
	}

	public void setMedicationConcentration(String medicationConcentration) {
		this.medicationConcentration = medicationConcentration;
	}

	@Column(name = "medication_size", nullable = false, length = 0)
	public String getMedicationSize() {
		return this.medicationSize;
	}

	public void setMedicationSize(String medicationSize) {
		this.medicationSize = medicationSize;
	}

	@Column(name = "unit")
	public Integer getUnit() {
		return this.unit;
	}

	public void setUnit(Integer unit) {
		this.unit = unit;
	}

	@Column(name = "amount", precision = 10)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "total", precision = 20)
	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}
}
