package co.com.tactusoft.crm.model.entities;

// Generated 24-abr-2013 14:52:22 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwRipsTransaction generated by hbm2java
 */
@Entity
@Table(name = "vw_rips_transaction", catalog = "crm_db")
public class VwRipsTransaction implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private VwRipsTransactionId id;

	public VwRipsTransaction() {
	}

	public VwRipsTransaction(VwRipsTransactionId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idBranch", column = @Column(name = "id_branch", nullable = false, scale = 0)),
			@AttributeOverride(name = "appointmentDate", column = @Column(name = "appointment_date", length = 10)),
			@AttributeOverride(name = "clinic", column = @Column(name = "clinic", length = 45)),
			@AttributeOverride(name = "docType", column = @Column(name = "doc_type", length = 2)),
			@AttributeOverride(name = "doc", column = @Column(name = "doc", length = 30)),
			@AttributeOverride(name = "idBill", column = @Column(name = "id_bill", nullable = false, length = 30)),
			@AttributeOverride(name = "dateBill", column = @Column(name = "date_bill", length = 19)),
			@AttributeOverride(name = "startDate", column = @Column(name = "start_date", nullable = false, length = 0)),
			@AttributeOverride(name = "endDate", column = @Column(name = "end_date", nullable = false, length = 0)),
			@AttributeOverride(name = "epsCode", column = @Column(name = "eps_code", nullable = false, length = 0)),
			@AttributeOverride(name = "epsName", column = @Column(name = "eps_name", nullable = false, length = 0)),
			@AttributeOverride(name = "contract", column = @Column(name = "contract", nullable = false, length = 0)),
			@AttributeOverride(name = "benefitPlan", column = @Column(name = "benefit_plan", nullable = false, length = 0)),
			@AttributeOverride(name = "policy", column = @Column(name = "policy", nullable = false, length = 0)),
			@AttributeOverride(name = "copayment", column = @Column(name = "copayment", nullable = false)),
			@AttributeOverride(name = "commission", column = @Column(name = "commission", nullable = false)),
			@AttributeOverride(name = "discount", column = @Column(name = "discount", nullable = false)),
			@AttributeOverride(name = "amount", column = @Column(name = "amount", precision = 10)),
			@AttributeOverride(name = "typeHistory", column = @Column(name = "type_history")) })
	public VwRipsTransactionId getId() {
		return this.id;
	}

	public void setId(VwRipsTransactionId id) {
		this.id = id;
	}

}
