package co.com.tactusoft.crm.model.entities;

// Generated 24-abr-2013 14:52:22 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwRipsProcedure generated by hbm2java
 */
@Entity
@Table(name = "vw_rips_procedure", catalog = "crm_db")
public class VwRipsProcedure implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private VwRipsProcedureId id;

	public VwRipsProcedure() {
	}

	public VwRipsProcedure(VwRipsProcedureId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idBranch", column = @Column(name = "id_branch", nullable = false, scale = 0)),
			@AttributeOverride(name = "appointmentDate", column = @Column(name = "appointment_date", length = 10)),
			@AttributeOverride(name = "idBill", column = @Column(name = "id_bill", nullable = false, length = 30)),
			@AttributeOverride(name = "clinic", column = @Column(name = "clinic", length = 45)),
			@AttributeOverride(name = "docType", column = @Column(name = "doc_type", length = 2)),
			@AttributeOverride(name = "doc", column = @Column(name = "doc", length = 30)),
			@AttributeOverride(name = "autorization", column = @Column(name = "autorization", nullable = false, length = 0)),
			@AttributeOverride(name = "procedureType", column = @Column(name = "procedure_type")),
			@AttributeOverride(name = "procedureCode", column = @Column(name = "procedure_code", length = 18)),
			@AttributeOverride(name = "procedureScope", column = @Column(name = "procedure_scope", nullable = false)),
			@AttributeOverride(name = "procedureTarget", column = @Column(name = "procedure_target", nullable = false)),
			@AttributeOverride(name = "personal", column = @Column(name = "personal", nullable = false, length = 0)),
			@AttributeOverride(name = "diagnosis1", column = @Column(name = "diagnosis_1", nullable = false, length = 0)),
			@AttributeOverride(name = "diagnosis2", column = @Column(name = "diagnosis_2", nullable = false, length = 0)),
			@AttributeOverride(name = "complication", column = @Column(name = "complication", nullable = false, length = 0)),
			@AttributeOverride(name = "surgical", column = @Column(name = "surgical", nullable = false, length = 0)),
			@AttributeOverride(name = "amount", column = @Column(name = "amount", precision = 10)) })
	public VwRipsProcedureId getId() {
		return this.id;
	}

	public void setId(VwRipsProcedureId id) {
		this.id = id;
	}

}
